package view;

import dao.UsuariosDAO;
import java.util.ArrayList;
import java.util.List;

public class JDlgConsultaUsuarios extends javax.swing.JDialog {

    ControllerConsultasUsuarios controllerConsultasUsuarios;

    public JDlgConsultaUsuarios(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        iniciarRelogio("Consulta de Usuários"); // coloque o nome do usuário logado aqui
        controllerConsultasUsuarios = new ControllerConsultasUsuarios();
        UsuariosDAO usuariosDAO = new UsuariosDAO();
        List lista = new ArrayList();
        controllerConsultasUsuarios.setList(lista);
        jTable.setModel(controllerConsultasUsuarios);
    }

    private void iniciarRelogio(String nomeUsuario) {
        javax.swing.Timer timer = new javax.swing.Timer(1000, e -> {
            java.text.SimpleDateFormat sdfHora = new java.text.SimpleDateFormat("HH:mm:ss");
            java.text.SimpleDateFormat sdfData = new java.text.SimpleDateFormat("EEEE, dd 'de' MMMM 'de' yyyy");

            String hora = sdfHora.format(new java.util.Date());
            String data = sdfData.format(new java.util.Date());

            // Capitaliza o dia da semana
            data = data.substring(0, 1).toUpperCase() + data.substring(1);

            // Define título com usuário, data e hora
            setTitle(nomeUsuario + " | " + data + " | " + hora);
        });
        timer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jBtnOk = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTxtApelido = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jBtnConsultar = new javax.swing.JButton();
        jBtnOk1 = new javax.swing.JButton();
        jTxtNome = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable);

        jBtnOk.setText("OK");
        jBtnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnOkActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome");

        jLabel2.setText("Apelido");

        jBtnConsultar.setText("Consultar");
        jBtnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConsultarActionPerformed(evt);
            }
        });

        jBtnOk1.setText("IMPRIMIR");
        jBtnOk1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnOk1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBtnOk1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtnOk))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(246, 246, 246)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTxtApelido, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jBtnConsultar)))
                        .addGap(0, 8, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxtApelido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtnConsultar))
                        .addGap(3, 3, 3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jTxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnOk)
                    .addComponent(jBtnOk1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnOkActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jBtnOkActionPerformed

    private void jTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMouseClicked
        if (evt.getClickCount() == 2) {
            jBtnOk1ActionPerformed(null);
        }
    }//GEN-LAST:event_jTableMouseClicked

    private void jBtnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConsultarActionPerformed
        UsuariosDAO usuariosDAO = new UsuariosDAO();
        List lista;
        if ((jTxtNome.getText().isEmpty() == false)
                && (jTxtApelido.getText().isEmpty() == false)) {
            lista = (List) usuariosDAO.listNomeApelido(jTxtNome.getText(),
                    (jTxtApelido.getText()));
        } else if (jTxtNome.getText().isEmpty() == false) {
            lista = (List) usuariosDAO.listNome(jTxtNome.getText());
        } else if (jTxtApelido.getText().isEmpty() == false) {
            lista = (List) usuariosDAO.listApelido(jTxtApelido.getText());
        } else {
            lista = (List) usuariosDAO.listAll();
        }
        controllerConsultasUsuarios.setList(lista);
    }//GEN-LAST:event_jBtnConsultarActionPerformed

    private void jBtnOk1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnOk1ActionPerformed
        try {
            // Verifica se há dados na tabela
            if (jTable.getRowCount() == 0) {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Não há dados para imprimir!\nRealize uma consulta primeiro.",
                        "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
                return;
            }

            // Configurar o serviço de impressão
            java.awt.print.PrinterJob job = java.awt.print.PrinterJob.getPrinterJob();
            job.setJobName("Relatório de Usuários Premium");

            // Criar um Printable personalizado
            java.awt.print.Printable printable = new java.awt.print.Printable() {
                @Override
                public int print(java.awt.Graphics graphics, java.awt.print.PageFormat pageFormat, int pageIndex)
                        throws java.awt.print.PrinterException {

                    if (pageIndex > 0) {
                        return NO_SUCH_PAGE;
                    }

                    java.awt.Graphics2D g2d = (java.awt.Graphics2D) graphics;
                    g2d.translate(pageFormat.getImageableX(), pageFormat.getImageableY());

                    // Ativar antialiasing para melhor qualidade
                    g2d.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING,
                            java.awt.RenderingHints.VALUE_ANTIALIAS_ON);
                    g2d.setRenderingHint(java.awt.RenderingHints.KEY_TEXT_ANTIALIASING,
                            java.awt.RenderingHints.VALUE_TEXT_ANTIALIAS_ON);

                    // Cores do tema premium preto e dourado
                    java.awt.Color gold = new java.awt.Color(212, 175, 55);
                    java.awt.Color darkGold = new java.awt.Color(170, 140, 45);
                    java.awt.Color black = new java.awt.Color(30, 30, 30);
                    java.awt.Color lightBlack = new java.awt.Color(60, 60, 60);
                    java.awt.Color white = java.awt.Color.WHITE;
                    java.awt.Color rowEven = new java.awt.Color(250, 250, 250);
                    java.awt.Color rowOdd = new java.awt.Color(240, 240, 240);
                    java.awt.Color activeGreen = new java.awt.Color(0, 150, 0);
                    java.awt.Color inactiveRed = new java.awt.Color(200, 0, 0);
                    java.awt.Color adminPurple = new java.awt.Color(128, 0, 128);

                    // Fundo da página
                    g2d.setColor(white);
                    g2d.fillRect(0, 0, (int) pageFormat.getImageableWidth(),
                            (int) pageFormat.getImageableHeight());

                    // Cabeçalho decorativo
                    g2d.setColor(gold);
                    g2d.fillRect(0, 0, (int) pageFormat.getImageableWidth(), 4);
                    g2d.fillRect(0, 0, 4, (int) pageFormat.getImageableHeight());

                    // Título com estilo premium
                    g2d.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 22));

                    // Sombra do título
                    g2d.setColor(new java.awt.Color(200, 200, 200));
                    g2d.drawString("RELATÓRIO DE USUÁRIOS", 102, 52);

                    // Título principal em dourado
                    g2d.setColor(gold);
                    g2d.drawString("RELATÓRIO DE USUÁRIOS", 100, 50);

                    // Linha decorativa abaixo do título
                    g2d.setStroke(new java.awt.BasicStroke(1.5f));
                    g2d.setColor(darkGold);
                    g2d.drawLine(100, 55, 320, 55);

                    // Ícone de usuários
                    g2d.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 16));
                    g2d.drawString("👥", 75, 55);

                    // Data
                    g2d.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 10));
                    g2d.setColor(lightBlack);
                    String data = new java.text.SimpleDateFormat("dd/MM/yyyy HH:mm:ss").format(new java.util.Date());
                    g2d.drawString("Gerado em: " + data, 100, 70);

                    // Filtros aplicados
                    g2d.setFont(new java.awt.Font("Segoe UI", java.awt.Font.ITALIC, 9));
                    g2d.setColor(black);
                    String filtros = "";

                    boolean primeiroFiltro = true;

                    // Filtro por Nome
                    if (!jTxtNome.getText().isEmpty()) {
                        filtros += "Nome: " + jTxtNome.getText();
                        primeiroFiltro = false;
                    }

                    // Filtro por Apelido
                    if (!jTxtApelido.getText().isEmpty()) {
                        if (!primeiroFiltro) {
                            filtros += " | ";
                        }
                        filtros += "Apelido: " + jTxtApelido.getText();
                    }

                    if (!filtros.isEmpty()) {
                        g2d.drawString("Filtros aplicados: " + filtros, 100, 85);

                        // Ícone de filtro
                        g2d.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 10));
                        g2d.drawString("🔍", 85, 85);
                    }

                    // Desenhar tabela
                    int y = 110;

                    // Cabeçalho da tabela
                    g2d.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 11));

                    // Calcular largura das colunas
                    int numColunas = jTable.getColumnCount();
                    int[] larguras = new int[numColunas];
                    int larguraTotal = 0;

                    // Ajustar larguras baseado no tipo de dado das colunas
                    for (int i = 0; i < numColunas; i++) {
                        String colunaNome = jTable.getColumnName(i).toLowerCase();

                        // Ajustar largura baseada no nome da coluna
                        if (colunaNome.contains("nome") || colunaNome.contains("usuário")
                                || colunaNome.contains("usuario") || colunaNome.contains("completo")) {
                            larguras[i] = 150; // Nomes completos
                        } else if (colunaNome.contains("apelido") || colunaNome.contains("login")
                                || colunaNome.contains("username") || colunaNome.contains("nickname")) {
                            larguras[i] = 120; // Apelidos/logins
                        } else if (colunaNome.contains("email") || colunaNome.contains("e-mail")) {
                            larguras[i] = 180; // Emails
                        } else if (colunaNome.contains("telefone") || colunaNome.contains("celular")
                                || colunaNome.contains("fone")) {
                            larguras[i] = 110; // Telefones
                        } else if (colunaNome.contains("cpf") || colunaNome.contains("rg")
                                || colunaNome.contains("documento")) {
                            larguras[i] = 110; // Documentos
                        } else if (colunaNome.contains("perfil") || colunaNome.contains("permission")
                                || colunaNome.contains("nivel") || colunaNome.contains("cargo")) {
                            larguras[i] = 100; // Perfis/permissões
                        } else if (colunaNome.contains("status") || colunaNome.contains("ativo")
                                || colunaNome.contains("situação")) {
                            larguras[i] = 80; // Status
                        } else if (colunaNome.contains("data") || colunaNome.contains("cadastro")
                                || colunaNome.contains("registro")) {
                            larguras[i] = 100; // Datas
                        } else if (colunaNome.contains("endereço") || colunaNome.contains("endereco")) {
                            larguras[i] = 160; // Endereços
                        } else {
                            larguras[i] = 120; // Largura padrão
                        }
                        larguraTotal += larguras[i];
                    }

                    // Desenhar cabeçalhos com estilo premium
                    int x = 30;
                    for (int i = 0; i < numColunas; i++) {
                        // Fundo gradiente do cabeçalho
                        java.awt.GradientPaint gradient = new java.awt.GradientPaint(
                                x, y - 12, black,
                                x, y + 8, new java.awt.Color(50, 50, 50)
                        );
                        g2d.setPaint(gradient);
                        g2d.fillRoundRect(x, y - 12, larguras[i], 20, 5, 5);

                        // Borda dourada
                        g2d.setColor(gold);
                        g2d.drawRoundRect(x, y - 12, larguras[i], 20, 5, 5);

                        // Texto do cabeçalho
                        g2d.setColor(white);
                        String coluna = jTable.getColumnName(i);

                        // Centralizar texto no cabeçalho
                        java.awt.FontMetrics fm = g2d.getFontMetrics();
                        int textWidth = fm.stringWidth(coluna);
                        int textX = x + (larguras[i] - textWidth) / 2;

                        g2d.drawString(coluna, textX, y);
                        x += larguras[i];
                    }

                    y += 15;

                    // Dados da tabela
                    g2d.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 10));

                    // Estatísticas
                    int ativos = 0;
                    int inativos = 0;
                    int admins = 0;
                    int usuariosComuns = 0;
                    int colunaStatusIndex = -1;
                    int colunaPerfilIndex = -1;

                    // Encontrar índices das colunas importantes
                    for (int i = 0; i < numColunas; i++) {
                        String colunaNome = jTable.getColumnName(i).toLowerCase();
                        if (colunaNome.contains("status") || colunaNome.contains("ativo")) {
                            colunaStatusIndex = i;
                        }
                        if (colunaNome.contains("perfil") || colunaNome.contains("nivel")
                                || colunaNome.contains("cargo") || colunaNome.contains("permission")) {
                            colunaPerfilIndex = i;
                        }
                    }

                    for (int row = 0; row < jTable.getRowCount(); row++) {
                        x = 30;

                        // Alternar cor de fundo das linhas
                        if (row % 2 == 0) {
                            g2d.setColor(rowEven);
                        } else {
                            g2d.setColor(rowOdd);
                        }
                        g2d.fillRect(30, y - 8, larguraTotal, 15);

                        // Borda sutil das linhas
                        g2d.setColor(new java.awt.Color(220, 220, 220));
                        g2d.drawRect(30, y - 8, larguraTotal, 15);

                        g2d.setColor(black);

                        for (int col = 0; col < numColunas; col++) {
                            Object valor = jTable.getValueAt(row, col);
                            String texto = "";

                            // Formatar dados
                            if (valor != null) {
                                String colunaNome = jTable.getColumnName(col).toLowerCase();
                                texto = valor.toString();

                                // Formatar dados específicos
                                if (colunaNome.contains("cpf")) {
                                    // Formatar CPF
                                    String cpf = texto.replaceAll("[^0-9]", "");
                                    if (cpf.length() == 11) {
                                        texto = cpf.substring(0, 3) + "." + cpf.substring(3, 6) + "."
                                                + cpf.substring(6, 9) + "-" + cpf.substring(9);
                                    }
                                } else if (colunaNome.contains("telefone") || colunaNome.contains("celular")) {
                                    // Formatar telefone
                                    String tel = texto.replaceAll("[^0-9]", "");
                                    if (tel.length() == 10) {
                                        texto = "(" + tel.substring(0, 2) + ") " + tel.substring(2, 6)
                                                + "-" + tel.substring(6);
                                    } else if (tel.length() == 11) {
                                        texto = "(" + tel.substring(0, 2) + ") " + tel.substring(2, 7)
                                                + "-" + tel.substring(7);
                                    }
                                } else if (colunaNome.contains("data") || colunaNome.contains("cadastro")) {
                                    // Formatar data
                                    try {
                                        java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("dd/MM/yyyy");
                                        java.util.Date dataObj = sdf.parse(texto);
                                        texto = sdf.format(dataObj);
                                    } catch (Exception e) {
                                        // Manter formato original se não conseguir parsear
                                    }
                                }

                                // Colorir baseado no status/perfil
                                if (col == colunaStatusIndex) {
                                    if (texto.equalsIgnoreCase("ativo") || texto.equals("1")
                                            || texto.equalsIgnoreCase("true") || texto.equalsIgnoreCase("sim")) {
                                        g2d.setColor(activeGreen);
                                        ativos++;
                                    } else {
                                        g2d.setColor(inactiveRed);
                                        inativos++;
                                    }
                                } else if (col == colunaPerfilIndex) {
                                    if (texto.equalsIgnoreCase("admin") || texto.equalsIgnoreCase("administrador")
                                            || texto.equalsIgnoreCase("superuser") || texto.contains("adm")) {
                                        g2d.setColor(adminPurple);
                                        admins++;
                                    } else {
                                        usuariosComuns++;
                                    }
                                }
                            }

                            // Truncar texto muito longo
                            String colunaNome = jTable.getColumnName(col).toLowerCase();
                            if (!colunaNome.contains("cpf") && !colunaNome.contains("telefone")
                                    && !colunaNome.contains("email") && texto.length() > 20) {
                                texto = texto.substring(0, 17) + "...";
                            }

                            g2d.drawString(texto, x + 5, y);

                            // Resetar cor para preto
                            g2d.setColor(black);

                            x += larguras[col];
                        }
                        y += 18;

                        // Verificar se cabe na página
                        if (y > pageFormat.getImageableHeight() - 120) {
                            return NO_SUCH_PAGE;
                        }
                    }

                    // Rodapé premium com estatísticas
                    int pageHeight = (int) pageFormat.getImageableHeight();

                    // Linha decorativa no rodapé
                    g2d.setColor(gold);
                    g2d.setStroke(new java.awt.BasicStroke(1.5f));
                    g2d.drawLine(30, pageHeight - 110, (int) pageFormat.getImageableWidth() - 30, pageHeight - 110);

                    // Seção de estatísticas
                    g2d.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 12));
                    g2d.setColor(black);
                    g2d.drawString("ESTATÍSTICAS DO SISTEMA", 30, pageHeight - 95);

                    // Estatísticas detalhadas
                    g2d.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 10));

                    // Total de usuários
                    int totalUsuarios = jTable.getRowCount();
                    g2d.setColor(lightBlack);
                    g2d.drawString("Total de usuários: ", 30, pageHeight - 80);
                    g2d.setColor(gold);
                    g2d.drawString(String.valueOf(totalUsuarios), 150, pageHeight - 80);

                    // Estatísticas de status
                    if (colunaStatusIndex != -1) {
                        g2d.setColor(lightBlack);
                        g2d.drawString("Usuários ativos: ", 30, pageHeight - 65);
                        g2d.setColor(activeGreen);
                        g2d.drawString(ativos + " (" + (totalUsuarios > 0
                                ? (ativos * 100 / totalUsuarios) : 0) + "%)", 150, pageHeight - 65);

                        g2d.setColor(lightBlack);
                        g2d.drawString("Usuários inativos: ", 30, pageHeight - 50);
                        g2d.setColor(inactiveRed);
                        g2d.drawString(inativos + " (" + (totalUsuarios > 0
                                ? (inativos * 100 / totalUsuarios) : 0) + "%)", 150, pageHeight - 50);
                    }

                    // Estatísticas de perfil
                    if (colunaPerfilIndex != -1) {
                        g2d.setColor(lightBlack);
                        g2d.drawString("Administradores: ", 200, pageHeight - 80);
                        g2d.setColor(adminPurple);
                        g2d.drawString(admins + " (" + (totalUsuarios > 0
                                ? (admins * 100 / totalUsuarios) : 0) + "%)", 300, pageHeight - 80);

                        g2d.setColor(lightBlack);
                        g2d.drawString("Usuários comuns: ", 200, pageHeight - 65);
                        g2d.setColor(new java.awt.Color(0, 100, 200)); // Azul para usuários comuns
                        g2d.drawString(usuariosComuns + " (" + (totalUsuarios > 0
                                ? (usuariosComuns * 100 / totalUsuarios) : 0) + "%)", 300, pageHeight - 65);
                    }

                    // Barra de distribuição
                    if (colunaStatusIndex != -1 && totalUsuarios > 0) {
                        int barStartX = 30;
                        int barWidth = 200;
                        int barHeight = 8;
                        int barY = pageHeight - 35;

                        // Barra de ativos
                        if (ativos > 0) {
                            int ativosWidth = (ativos * barWidth) / totalUsuarios;
                            g2d.setColor(activeGreen);
                            g2d.fillRect(barStartX, barY, ativosWidth, barHeight);
                        }

                        // Barra de inativos
                        if (inativos > 0) {
                            int inativosWidth = (inativos * barWidth) / totalUsuarios;
                            g2d.setColor(inactiveRed);
                            g2d.fillRect(barStartX + (ativos * barWidth) / totalUsuarios, barY, inativosWidth, barHeight);
                        }

                        // Legenda da barra
                        g2d.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 8));
                        g2d.setColor(lightBlack);
                        g2d.drawString("Distribuição: ", barStartX, barY - 5);
                        g2d.setColor(activeGreen);
                        g2d.drawString("■ Ativos ", barStartX + 70, barY - 5);
                        g2d.setColor(inactiveRed);
                        g2d.drawString("■ Inativos ", barStartX + 120, barY - 5);
                    }

                    // Número da página
                    g2d.setFont(new java.awt.Font("Segoe UI", java.awt.Font.ITALIC, 9));
                    g2d.setColor(lightBlack);
                    g2d.drawString("Página 1 de 1", (int) pageFormat.getImageableWidth() - 80, pageHeight - 15);

                    // Logo/assinatura com ícone de segurança
                    g2d.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 10));
                    g2d.setColor(gold);
                    g2d.drawString("🔒 Sistema Seguro de Usuários",
                            (int) pageFormat.getImageableWidth() - 200, pageHeight - 5);

                    return PAGE_EXISTS;
                }
            };

            job.setPrintable(printable);

            // Mostrar diálogo de impressão
            if (job.printDialog()) {
                job.print();
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Relatório premium de usuários gerado com sucesso!\n\n"
                        + "Para salvar como PDF, selecione 'Microsoft Print to PDF'\n"
                        + "ou outra impressora virtual de PDF na lista de impressoras.",
                        "Relatório Premium", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            }

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Erro ao gerar relatório premium: " + e.getMessage(),
                    "Erro", javax.swing.JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_jBtnOk1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgConsultaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgConsultaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgConsultaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgConsultaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgConsultaUsuarios dialog = new JDlgConsultaUsuarios(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnConsultar;
    private javax.swing.JButton jBtnOk;
    private javax.swing.JButton jBtnOk1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable;
    private javax.swing.JTextField jTxtApelido;
    private javax.swing.JTextField jTxtNome;
    // End of variables declaration//GEN-END:variables
}
