package view;

import dao.ProdutosDAO;
import static java.awt.print.Printable.NO_SUCH_PAGE;
import static java.awt.print.Printable.PAGE_EXISTS;
import java.util.ArrayList;
import java.util.List;
import tools.Util;

public class JDlgConsultaProdutos extends javax.swing.JDialog {

    ControllerConsultasProdutos controllerConsultasProdutos;

    public JDlgConsultaProdutos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        iniciarRelogio("Consulta de Produtos"); // coloque o nome do usuário logado aqui
        controllerConsultasProdutos = new ControllerConsultasProdutos();
        ProdutosDAO produtosDAO = new ProdutosDAO();
        List lista = new ArrayList();
        controllerConsultasProdutos.setList(lista);
        jTable.setModel(controllerConsultasProdutos);
    }

    private void iniciarRelogio(String nomeUsuario) {
        javax.swing.Timer timer = new javax.swing.Timer(1000, e -> {
            java.text.SimpleDateFormat sdfHora = new java.text.SimpleDateFormat("HH:mm:ss");
            java.text.SimpleDateFormat sdfData = new java.text.SimpleDateFormat("EEEE, dd 'de' MMMM 'de' yyyy");

            String hora = sdfHora.format(new java.util.Date());
            String data = sdfData.format(new java.util.Date());

            // Capitaliza o dia da semana
            data = data.substring(0, 1).toUpperCase() + data.substring(1);

            // Define título com usuário, data e hora
            setTitle(nomeUsuario + " | " + data + " | " + hora);
        });
        timer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jBtnOk = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTxtNome = new javax.swing.JTextField();
        jTxtValor = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jBtnConsultar = new javax.swing.JButton();
        jBtnOk1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable);

        jBtnOk.setText("OK");
        jBtnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnOkActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome");

        jLabel2.setText("Valor Maior que ");

        jBtnConsultar.setText("Consultar");
        jBtnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConsultarActionPerformed(evt);
            }
        });

        jBtnOk1.setText("IMPRIMIR");
        jBtnOk1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnOk1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBtnOk1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtnOk))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jTxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTxtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnConsultar)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtnConsultar))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnOk)
                    .addComponent(jBtnOk1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnOkActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jBtnOkActionPerformed

    private void jTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMouseClicked
        if (evt.getClickCount() == 2) {
            jBtnOk1ActionPerformed(null);
        }
    }//GEN-LAST:event_jTableMouseClicked

    private void jBtnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConsultarActionPerformed
        ProdutosDAO produtosDAO = new ProdutosDAO();
        List lista;
        if ((jTxtNome.getText().isEmpty() == false)
                && (jTxtValor.getText().isEmpty() == false)) {
            lista = (List) produtosDAO.listNomeValor(jTxtNome.getText(),
                    Util.strToDouble(jTxtValor.getText()));
        } else if (jTxtNome.getText().isEmpty() == false) {
            lista = (List) produtosDAO.listNome(jTxtNome.getText());
        } else if (jTxtValor.getText().isEmpty() == false) {
            lista = (List) produtosDAO.listValor(Util.strToDouble(jTxtValor.getText()));
        } else {
            lista = (List) produtosDAO.listAll();
        }
        controllerConsultasProdutos.setList(lista);


    }//GEN-LAST:event_jBtnConsultarActionPerformed

    private void jBtnOk1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnOk1ActionPerformed
        try {
            // Verifica se há dados na tabela
            if (jTable.getRowCount() == 0) {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Não há dados para imprimir!\nRealize uma consulta primeiro.",
                        "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
                return;
            }

            // Configurar o serviço de impressão
            java.awt.print.PrinterJob job = java.awt.print.PrinterJob.getPrinterJob();
            job.setJobName("Relatório de Produtos Premium");

            // Criar um Printable personalizado
            java.awt.print.Printable printable = new java.awt.print.Printable() {
                @Override
                public int print(java.awt.Graphics graphics, java.awt.print.PageFormat pageFormat, int pageIndex)
                        throws java.awt.print.PrinterException {

                    if (pageIndex > 0) {
                        return NO_SUCH_PAGE;
                    }

                    java.awt.Graphics2D g2d = (java.awt.Graphics2D) graphics;
                    g2d.translate(pageFormat.getImageableX(), pageFormat.getImageableY());

                    // Ativar antialiasing para melhor qualidade
                    g2d.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING,
                            java.awt.RenderingHints.VALUE_ANTIALIAS_ON);
                    g2d.setRenderingHint(java.awt.RenderingHints.KEY_TEXT_ANTIALIASING,
                            java.awt.RenderingHints.VALUE_TEXT_ANTIALIAS_ON);

                    // Cores do tema premium preto e dourado
                    java.awt.Color gold = new java.awt.Color(212, 175, 55);
                    java.awt.Color darkGold = new java.awt.Color(170, 140, 45);
                    java.awt.Color black = new java.awt.Color(30, 30, 30);
                    java.awt.Color lightBlack = new java.awt.Color(60, 60, 60);
                    java.awt.Color white = java.awt.Color.WHITE;
                    java.awt.Color rowEven = new java.awt.Color(250, 250, 250);
                    java.awt.Color rowOdd = new java.awt.Color(240, 240, 240);
                    java.awt.Color profitGreen = new java.awt.Color(0, 150, 0);
                    java.awt.Color lossRed = new java.awt.Color(200, 0, 0);

                    // Fundo da página
                    g2d.setColor(white);
                    g2d.fillRect(0, 0, (int) pageFormat.getImageableWidth(),
                            (int) pageFormat.getImageableHeight());

                    // Cabeçalho decorativo
                    g2d.setColor(gold);
                    g2d.fillRect(0, 0, (int) pageFormat.getImageableWidth(), 4);
                    g2d.fillRect(0, 0, 4, (int) pageFormat.getImageableHeight());

                    // Título com estilo premium
                    g2d.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 22));

                    // Sombra do título
                    g2d.setColor(new java.awt.Color(200, 200, 200));
                    g2d.drawString("RELATÓRIO DE PRODUTOS", 102, 52);

                    // Título principal em dourado
                    g2d.setColor(gold);
                    g2d.drawString("RELATÓRIO DE PRODUTOS", 100, 50);

                    // Linha decorativa abaixo do título
                    g2d.setStroke(new java.awt.BasicStroke(1.5f));
                    g2d.setColor(darkGold);
                    g2d.drawLine(100, 55, 320, 55);

                    // Ícone de produtos (opcional)
                    g2d.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 16));
                    g2d.drawString("📦", 75, 55);

                    // Data
                    g2d.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 10));
                    g2d.setColor(lightBlack);
                    String data = new java.text.SimpleDateFormat("dd/MM/yyyy HH:mm:ss").format(new java.util.Date());
                    g2d.drawString("Gerado em: " + data, 100, 70);

                    // Filtros aplicados
                    g2d.setFont(new java.awt.Font("Segoe UI", java.awt.Font.ITALIC, 9));
                    g2d.setColor(black);
                    String filtros = "";

                    // Filtro por Nome
                    if (!jTxtNome.getText().isEmpty()) {
                        filtros += "Nome: " + jTxtNome.getText();
                    }

                    // Filtro por Valor maior que
                    if (!jTxtValor.getText().isEmpty()) {
                        try {
                            double valor = Double.parseDouble(jTxtValor.getText());
                            if (!filtros.isEmpty()) {
                                filtros += " | ";
                            }
                            filtros += "Valor > R$ " + String.format("%.2f", valor);
                        } catch (NumberFormatException e) {
                            // Ignorar se o valor não for numérico
                        }
                    }

                    if (!filtros.isEmpty()) {
                        g2d.drawString("Filtros aplicados: " + filtros, 100, 85);

                        // Ícone de filtro
                        g2d.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 10));
                        g2d.drawString("🔍", 85, 85);
                    }

                    // Desenhar tabela
                    int y = 110;

                    // Cabeçalho da tabela
                    g2d.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 11));

                    // Calcular largura das colunas
                    int numColunas = jTable.getColumnCount();
                    int[] larguras = new int[numColunas];
                    int larguraTotal = 0;

                    // Ajustar larguras baseado no tipo de dado das colunas
                    for (int i = 0; i < numColunas; i++) {
                        String colunaNome = jTable.getColumnName(i).toLowerCase();

                        // Ajustar largura baseada no nome da coluna
                        if (colunaNome.contains("valor") || colunaNome.contains("preço")
                                || colunaNome.contains("custo") || colunaNome.contains("lucro")) {
                            larguras[i] = 110; // Colunas de valores
                        } else if (colunaNome.contains("nome") || colunaNome.contains("descrição")
                                || colunaNome.contains("produto")) {
                            larguras[i] = 160; // Nome/descrição do produto
                        } else if (colunaNome.contains("quantidade") || colunaNome.contains("estoque")
                                || colunaNome.contains("qtd")) {
                            larguras[i] = 90; // Quantidades
                        } else if (colunaNome.contains("código") || colunaNome.contains("codigo")
                                || colunaNome.contains("id")) {
                            larguras[i] = 80; // Códigos/IDs
                        } else if (colunaNome.contains("categoria") || colunaNome.contains("marca")) {
                            larguras[i] = 120; // Categorias
                        } else if (colunaNome.contains("data") || colunaNome.contains("cadastro")) {
                            larguras[i] = 100; // Datas
                        } else {
                            larguras[i] = 130; // Largura padrão
                        }
                        larguraTotal += larguras[i];
                    }

                    // Desenhar cabeçalhos com estilo premium
                    int x = 30;
                    for (int i = 0; i < numColunas; i++) {
                        // Fundo gradiente do cabeçalho
                        java.awt.GradientPaint gradient = new java.awt.GradientPaint(
                                x, y - 12, black,
                                x, y + 8, new java.awt.Color(50, 50, 50)
                        );
                        g2d.setPaint(gradient);
                        g2d.fillRoundRect(x, y - 12, larguras[i], 20, 5, 5);

                        // Borda dourada
                        g2d.setColor(gold);
                        g2d.drawRoundRect(x, y - 12, larguras[i], 20, 5, 5);

                        // Texto do cabeçalho
                        g2d.setColor(white);
                        String coluna = jTable.getColumnName(i);

                        // Centralizar texto no cabeçalho
                        java.awt.FontMetrics fm = g2d.getFontMetrics();
                        int textWidth = fm.stringWidth(coluna);
                        int textX = x + (larguras[i] - textWidth) / 2;

                        g2d.drawString(coluna, textX, y);
                        x += larguras[i];
                    }

                    y += 15;

                    // Dados da tabela
                    g2d.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 10));

                    // Variáveis para cálculos
                    double valorTotal = 0;
                    double maiorValor = 0;
                    double menorValor = Double.MAX_VALUE;
                    int colunaValorIndex = -1;

                    // Encontrar índice da coluna de valor
                    for (int i = 0; i < numColunas; i++) {
                        if (jTable.getColumnName(i).toLowerCase().contains("valor")
                                || jTable.getColumnName(i).toLowerCase().contains("preço")) {
                            colunaValorIndex = i;
                            break;
                        }
                    }

                    for (int row = 0; row < jTable.getRowCount(); row++) {
                        x = 30;

                        // Alternar cor de fundo das linhas
                        if (row % 2 == 0) {
                            g2d.setColor(rowEven);
                        } else {
                            g2d.setColor(rowOdd);
                        }
                        g2d.fillRect(30, y - 8, larguraTotal, 15);

                        // Borda sutil das linhas
                        g2d.setColor(new java.awt.Color(220, 220, 220));
                        g2d.drawRect(30, y - 8, larguraTotal, 15);

                        g2d.setColor(black);

                        for (int col = 0; col < numColunas; col++) {
                            Object valor = jTable.getValueAt(row, col);
                            String texto = "";

                            // Formatar valores
                            if (valor != null) {
                                String colunaNome = jTable.getColumnName(col).toLowerCase();

                                if (colunaNome.contains("valor") || colunaNome.contains("preço")
                                        || colunaNome.contains("custo") || colunaNome.contains("lucro")) {
                                    try {
                                        // Formatar como moeda
                                        double numValor = Double.parseDouble(valor.toString());
                                        texto = String.format("R$ %.2f", numValor);

                                        // Calcular totais
                                        if (colunaNome.contains("valor") || colunaNome.contains("preço")) {
                                            valorTotal += numValor;
                                            if (numValor > maiorValor) {
                                                maiorValor = numValor;
                                            }
                                            if (numValor < menorValor) {
                                                menorValor = numValor;
                                            }
                                        }

                                        // Colorir baseado no valor (lucro/desconto)
                                        if (colunaNome.contains("lucro")) {
                                            if (numValor > 0) {
                                                g2d.setColor(profitGreen);
                                            } else if (numValor < 0) {
                                                g2d.setColor(lossRed);
                                            }
                                        }
                                    } catch (NumberFormatException e) {
                                        texto = valor.toString();
                                    }
                                } else if (colunaNome.contains("quantidade") || colunaNome.contains("estoque")) {
                                    // Destacar estoque baixo
                                    try {
                                        int qtd = Integer.parseInt(valor.toString());
                                        if (qtd <= 5) {
                                            g2d.setColor(lossRed);
                                            texto = valor.toString() + " ⚠";
                                        } else {
                                            texto = valor.toString();
                                        }
                                    } catch (NumberFormatException e) {
                                        texto = valor.toString();
                                    }
                                } else {
                                    texto = valor.toString();
                                }
                            }

                            // Truncar texto muito longo
                            String colunaNome = jTable.getColumnName(col).toLowerCase();
                            if (!colunaNome.contains("valor") && !colunaNome.contains("preço")
                                    && !colunaNome.contains("custo") && texto.length() > 25) {
                                texto = texto.substring(0, 22) + "...";
                            }

                            g2d.drawString(texto, x + 5, y);

                            // Resetar cor
                            g2d.setColor(black);

                            x += larguras[col];
                        }
                        y += 18;

                        // Verificar se cabe na página
                        if (y > pageFormat.getImageableHeight() - 100) {
                            return NO_SUCH_PAGE;
                        }
                    }

                    // Rodapé premium com estatísticas
                    int pageHeight = (int) pageFormat.getImageableHeight();

                    // Linha decorativa no rodapé
                    g2d.setColor(gold);
                    g2d.setStroke(new java.awt.BasicStroke(1.5f));
                    g2d.drawLine(30, pageHeight - 90, (int) pageFormat.getImageableWidth() - 30, pageHeight - 90);

                    // Seção de resumo financeiro
                    g2d.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 12));
                    g2d.setColor(black);
                    g2d.drawString("RESUMO FINANCEIRO", 30, pageHeight - 75);

                    // Estatísticas
                    g2d.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 10));
                    g2d.setColor(lightBlack);

                    // Total de produtos
                    g2d.drawString("Total de produtos: ", 30, pageHeight - 60);
                    g2d.setColor(gold);
                    g2d.drawString(String.valueOf(jTable.getRowCount()), 150, pageHeight - 60);

                    // Valor total
                    g2d.setColor(lightBlack);
                    g2d.drawString("Valor total em estoque: ", 30, pageHeight - 45);
                    g2d.setColor(profitGreen);
                    g2d.drawString("R$ " + String.format("%.2f", valorTotal), 180, pageHeight - 45);

                    // Valor médio
                    if (jTable.getRowCount() > 0) {
                        double valorMedio = valorTotal / jTable.getRowCount();
                        g2d.setColor(lightBlack);
                        g2d.drawString("Valor médio: ", 30, pageHeight - 30);
                        g2d.setColor(black);
                        g2d.drawString("R$ " + String.format("%.2f", valorMedio), 150, pageHeight - 30);
                    }

                    // Maior e menor valor (se encontrados)
                    if (colunaValorIndex != -1 && jTable.getRowCount() > 0) {
                        g2d.setColor(lightBlack);
                        g2d.drawString("Maior valor: ", 250, pageHeight - 60);
                        g2d.setColor(profitGreen);
                        g2d.drawString("R$ " + String.format("%.2f", maiorValor), 330, pageHeight - 60);

                        g2d.setColor(lightBlack);
                        g2d.drawString("Menor valor: ", 250, pageHeight - 45);
                        g2d.setColor(new java.awt.Color(255, 140, 0)); // Laranja
                        g2d.drawString("R$ " + String.format("%.2f", menorValor), 330, pageHeight - 45);
                    }

                    // Calcular valor total por categoria (se houver coluna de categoria)
                    java.util.Map<String, Double> categoriasValor = new java.util.HashMap<>();
                    int categoriaIndex = -1;

                    for (int i = 0; i < numColunas; i++) {
                        if (jTable.getColumnName(i).toLowerCase().contains("categoria")) {
                            categoriaIndex = i;
                            break;
                        }
                    }

                    if (categoriaIndex != -1 && colunaValorIndex != -1) {
                        for (int row = 0; row < jTable.getRowCount(); row++) {
                            Object categoriaObj = jTable.getValueAt(row, categoriaIndex);
                            Object valorObj = jTable.getValueAt(row, colunaValorIndex);

                            if (categoriaObj != null && valorObj != null) {
                                try {
                                    String categoria = categoriaObj.toString();
                                    double valor = Double.parseDouble(valorObj.toString());

                                    categoriasValor.put(categoria,
                                            categoriasValor.getOrDefault(categoria, 0.0) + valor);
                                } catch (NumberFormatException e) {
                                    // Ignorar valores não numéricos
                                }
                            }
                        }
                    }

                    // Número da página
                    g2d.setFont(new java.awt.Font("Segoe UI", java.awt.Font.ITALIC, 9));
                    g2d.setColor(lightBlack);
                    g2d.drawString("Página 1 de 1", (int) pageFormat.getImageableWidth() - 80, pageHeight - 15);

                    // Logo/assinatura
                    g2d.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 10));
                    g2d.setColor(gold);
                    g2d.drawString("© Sistema Premium de Produtos",
                            (int) pageFormat.getImageableWidth() - 180, pageHeight - 5);

                    return PAGE_EXISTS;
                }
            };

            job.setPrintable(printable);

            // Mostrar diálogo de impressão
            if (job.printDialog()) {
                job.print();
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Relatório premium de produtos gerado com sucesso!\n\n"
                        + "Para salvar como PDF, selecione 'Microsoft Print to PDF'\n"
                        + "ou outra impressora virtual de PDF na lista de impressoras.",
                        "Relatório Premium", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            }

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Erro ao gerar relatório premium: " + e.getMessage(),
                    "Erro", javax.swing.JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_jBtnOk1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgConsultaProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgConsultaProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgConsultaProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgConsultaProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgConsultaProdutos dialog = new JDlgConsultaProdutos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnConsultar;
    private javax.swing.JButton jBtnOk;
    private javax.swing.JButton jBtnOk1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable;
    private javax.swing.JTextField jTxtNome;
    private javax.swing.JTextField jTxtValor;
    // End of variables declaration//GEN-END:variables
}
