package view;

import dao.ClientesDAO;
import java.util.ArrayList;
import java.util.List;

public class JDlgConsultaClientes extends javax.swing.JDialog {

    ControllerConsultasClientes controllerConsultasClientes;

    public JDlgConsultaClientes(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        iniciarRelogio("Consulta de Clientes"); // coloque o nome do usuário logado aqui
        controllerConsultasClientes = new ControllerConsultasClientes();
        ClientesDAO clientesDAO = new ClientesDAO();
        List lista = new ArrayList();
        controllerConsultasClientes.setList(lista);
        jTable.setModel(controllerConsultasClientes);
    }

    private void iniciarRelogio(String nomeUsuario) {
        javax.swing.Timer timer = new javax.swing.Timer(1000, e -> {
            java.text.SimpleDateFormat sdfHora = new java.text.SimpleDateFormat("HH:mm:ss");
            java.text.SimpleDateFormat sdfData = new java.text.SimpleDateFormat("EEEE, dd 'de' MMMM 'de' yyyy");

            String hora = sdfHora.format(new java.util.Date());
            String data = sdfData.format(new java.util.Date());

            // Capitaliza o dia da semana
            data = data.substring(0, 1).toUpperCase() + data.substring(1);

            // Define título com usuário, data e hora
            setTitle(nomeUsuario + " | " + data + " | " + hora);
        });
        timer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jBtnOk = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTxtNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jBtnConsultar = new javax.swing.JButton();
        jBtnOk1 = new javax.swing.JButton();
        jCboGenero = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable);

        jBtnOk.setText("OK");
        jBtnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnOkActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome");

        jLabel2.setText("Gênero");

        jBtnConsultar.setText("Consultar");
        jBtnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConsultarActionPerformed(evt);
            }
        });

        jBtnOk1.setText("IMPRIMIR");
        jBtnOk1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnOk1ActionPerformed(evt);
            }
        });

        jCboGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Feminino" }));
        jCboGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCboGeneroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBtnOk1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtnOk))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jTxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jCboGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(95, 95, 95)
                                .addComponent(jBtnConsultar)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnConsultar)
                    .addComponent(jCboGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnOk)
                    .addComponent(jBtnOk1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnOkActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jBtnOkActionPerformed

    private void jTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMouseClicked
        if (evt.getClickCount() == 2) {
            jBtnOk1ActionPerformed(null);
        }
    }//GEN-LAST:event_jTableMouseClicked

    private void jBtnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConsultarActionPerformed
        ClientesDAO usuariosDAO = new ClientesDAO();
        List lista;
        if ((jTxtNome.getText().isEmpty() == false)
                && (jCboGenero.getSelectedIndex() != -1)) {
            lista = (List) usuariosDAO.listNomeGenero(jTxtNome.getText(),
                    (jCboGenero.getSelectedIndex()));
        } else if (jTxtNome.getText().isEmpty() == false) {
            lista = (List) usuariosDAO.listNome(jTxtNome.getText());
        } else if (jCboGenero.getSelectedIndex() != -1) {
            lista = (List) usuariosDAO.listGenero(jCboGenero.getSelectedIndex());
        } else {
            lista = (List) usuariosDAO.listAll();
        }
        controllerConsultasClientes.setList(lista);


    }//GEN-LAST:event_jBtnConsultarActionPerformed

    private void jBtnOk1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnOk1ActionPerformed
        try {
            // Verifica se há dados na tabela
            if (jTable.getRowCount() == 0) {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Não há dados para imprimir!\nRealize uma consulta primeiro.",
                        "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
                return;
            }

            // Configurar o serviço de impressão
            java.awt.print.PrinterJob job = java.awt.print.PrinterJob.getPrinterJob();
            job.setJobName("Relatório de Clientes Premium");

            // Criar um Printable personalizado
            java.awt.print.Printable printable = new java.awt.print.Printable() {
                @Override
                public int print(java.awt.Graphics graphics, java.awt.print.PageFormat pageFormat, int pageIndex)
                        throws java.awt.print.PrinterException {

                    if (pageIndex > 0) {
                        return NO_SUCH_PAGE;
                    }

                    java.awt.Graphics2D g2d = (java.awt.Graphics2D) graphics;
                    g2d.translate(pageFormat.getImageableX(), pageFormat.getImageableY());

                    // Ativar antialiasing para melhor qualidade
                    g2d.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING,
                            java.awt.RenderingHints.VALUE_ANTIALIAS_ON);
                    g2d.setRenderingHint(java.awt.RenderingHints.KEY_TEXT_ANTIALIASING,
                            java.awt.RenderingHints.VALUE_TEXT_ANTIALIAS_ON);

                    // Cores do tema premium preto e dourado
                    java.awt.Color gold = new java.awt.Color(212, 175, 55);
                    java.awt.Color darkGold = new java.awt.Color(170, 140, 45);
                    java.awt.Color black = new java.awt.Color(30, 30, 30);
                    java.awt.Color lightBlack = new java.awt.Color(60, 60, 60);
                    java.awt.Color white = java.awt.Color.WHITE;
                    java.awt.Color rowEven = new java.awt.Color(250, 250, 250);
                    java.awt.Color rowOdd = new java.awt.Color(240, 240, 240);

                    // Fundo da página
                    g2d.setColor(white);
                    g2d.fillRect(0, 0, (int) pageFormat.getImageableWidth(),
                            (int) pageFormat.getImageableHeight());

                    // Cabeçalho decorativo
                    g2d.setColor(gold);
                    g2d.fillRect(0, 0, (int) pageFormat.getImageableWidth(), 4);
                    g2d.fillRect(0, 0, 4, (int) pageFormat.getImageableHeight());

                    // Título com estilo premium
                    g2d.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 22));

                    // Sombra do título
                    g2d.setColor(new java.awt.Color(200, 200, 200));
                    g2d.drawString("RELATÓRIO DE CLIENTES", 102, 52);

                    // Título principal em dourado
                    g2d.setColor(gold);
                    g2d.drawString("RELATÓRIO DE CLIENTES", 100, 50);

                    // Linha decorativa abaixo do título
                    g2d.setStroke(new java.awt.BasicStroke(1.5f));
                    g2d.setColor(darkGold);
                    g2d.drawLine(100, 55, 300, 55);

                    // Data
                    g2d.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 10));
                    g2d.setColor(lightBlack);
                    String data = new java.text.SimpleDateFormat("dd/MM/yyyy HH:mm:ss").format(new java.util.Date());
                    g2d.drawString("Gerado em: " + data, 100, 70);

                    // Filtros aplicados
                    g2d.setFont(new java.awt.Font("Segoe UI", java.awt.Font.ITALIC, 9));
                    String filtros = "";

                    // Filtro por Nome
                    if (!jTxtNome.getText().isEmpty()) {
                        filtros += "Nome: " + jTxtNome.getText();
                    }

                    // Filtro por Gênero
                    if (jCboGenero.getSelectedItem() != null) {
                        Object itemSelecionado = jCboGenero.getSelectedItem();
                        String generoSelecionado = itemSelecionado.toString().trim();

                        // Converter valor numérico para texto
                        if (generoSelecionado.equals("0")) {
                            generoSelecionado = "Masculino";
                        } else if (generoSelecionado.equals("1")) {
                            generoSelecionado = "Feminino";
                        }

                        // Verificar se não é o item padrão ou vazio
                        if (!generoSelecionado.isEmpty()
                                && !generoSelecionado.equals("Selecione...")
                                && !generoSelecionado.equals("Todos")
                                && !generoSelecionado.equals("0")
                                && !generoSelecionado.equals("1")) {

                            if (!filtros.isEmpty()) {
                                filtros += " | ";
                            }
                            filtros += "Gênero: " + generoSelecionado;
                        }
                    }

                    if (!filtros.isEmpty()) {
                        g2d.setColor(black);
                        g2d.drawString("Filtros aplicados: " + filtros, 100, 85);
                    }

                    // Desenhar tabela
                    int y = 110;

                    // Cabeçalho da tabela
                    g2d.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 11));

                    // Calcular largura das colunas
                    int numColunas = jTable.getColumnCount();
                    int[] larguras = new int[numColunas];
                    int larguraTotal = 0;

                    // Ajustar larguras baseado no tipo de dado das colunas
                    for (int i = 0; i < numColunas; i++) {
                        String colunaNome = jTable.getColumnName(i).toLowerCase();

                        // Ajustar largura baseada no nome da coluna
                        if (colunaNome.contains("nome") || colunaNome.contains("cliente")) {
                            larguras[i] = 150;
                        } else if (colunaNome.contains("email")) {
                            larguras[i] = 180;
                        } else if (colunaNome.contains("telefone") || colunaNome.contains("celular")) {
                            larguras[i] = 120;
                        } else if (colunaNome.contains("cpf") || colunaNome.contains("cnpj")) {
                            larguras[i] = 110;
                        } else if (colunaNome.contains("gênero") || colunaNome.contains("genero")
                                || colunaNome.contains("sexo")) {
                            larguras[i] = 100;
                        } else if (colunaNome.contains("data") || colunaNome.contains("nascimento")) {
                            larguras[i] = 100;
                        } else if (colunaNome.contains("endereço") || colunaNome.contains("endereco")) {
                            larguras[i] = 200;
                        } else if (colunaNome.contains("cidade") || colunaNome.contains("estado")) {
                            larguras[i] = 100;
                        } else {
                            larguras[i] = 120;
                        }
                        larguraTotal += larguras[i];
                    }

                    // Desenhar cabeçalhos com estilo premium
                    int x = 30;
                    for (int i = 0; i < numColunas; i++) {
                        // Fundo gradiente do cabeçalho
                        java.awt.GradientPaint gradient = new java.awt.GradientPaint(
                                x, y - 12, black,
                                x, y + 8, new java.awt.Color(50, 50, 50)
                        );
                        g2d.setPaint(gradient);
                        g2d.fillRoundRect(x, y - 12, larguras[i], 20, 5, 5);

                        // Borda dourada
                        g2d.setColor(gold);
                        g2d.drawRoundRect(x, y - 12, larguras[i], 20, 5, 5);

                        // Texto do cabeçalho
                        g2d.setColor(white);
                        String coluna = jTable.getColumnName(i);

                        // Centralizar texto no cabeçalho
                        java.awt.FontMetrics fm = g2d.getFontMetrics();
                        int textWidth = fm.stringWidth(coluna);
                        int textX = x + (larguras[i] - textWidth) / 2;

                        g2d.drawString(coluna, textX, y);
                        x += larguras[i];
                    }

                    y += 15;

                    // Dados da tabela
                    g2d.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 10));

                    for (int row = 0; row < jTable.getRowCount(); row++) {
                        x = 30;

                        // Alternar cor de fundo das linhas
                        if (row % 2 == 0) {
                            g2d.setColor(rowEven);
                        } else {
                            g2d.setColor(rowOdd);
                        }
                        g2d.fillRect(30, y - 8, larguraTotal, 15);

                        // Borda sutil das linhas
                        g2d.setColor(new java.awt.Color(220, 220, 220));
                        g2d.drawRect(30, y - 8, larguraTotal, 15);

                        g2d.setColor(black);

                        for (int col = 0; col < numColunas; col++) {
                            Object valor = jTable.getValueAt(row, col);
                            String texto = "";

                            if (valor != null) {
                                String colunaNome = jTable.getColumnName(col).toLowerCase();

                                // Formatar dados específicos
                                if (colunaNome.contains("cpf")) {
                                    String cpf = valor.toString().replaceAll("[^0-9]", "");
                                    if (cpf.length() == 11) {
                                        texto = cpf.substring(0, 3) + "."
                                                + cpf.substring(3, 6) + "."
                                                + cpf.substring(6, 9) + "-"
                                                + cpf.substring(9);
                                    } else {
                                        texto = valor.toString();
                                    }
                                } else if (colunaNome.contains("cnpj")) {
                                    String cnpj = valor.toString().replaceAll("[^0-9]", "");
                                    if (cnpj.length() == 14) {
                                        texto = cnpj.substring(0, 2) + "."
                                                + cnpj.substring(2, 5) + "."
                                                + cnpj.substring(5, 8) + "/"
                                                + cnpj.substring(8, 12) + "-"
                                                + cnpj.substring(12);
                                    } else {
                                        texto = valor.toString();
                                    }
                                } else if (colunaNome.contains("telefone") || colunaNome.contains("celular")) {
                                    String tel = valor.toString().replaceAll("[^0-9]", "");
                                    if (tel.length() == 10) {
                                        texto = "(" + tel.substring(0, 2) + ") "
                                                + tel.substring(2, 6) + "-"
                                                + tel.substring(6);
                                    } else if (tel.length() == 11) {
                                        texto = "(" + tel.substring(0, 2) + ") "
                                                + tel.substring(2, 7) + "-"
                                                + tel.substring(7);
                                    } else {
                                        texto = valor.toString();
                                    }
                                } else if (colunaNome.contains("data") || colunaNome.contains("nascimento")) {
                                    try {
                                        java.util.Date dataObj = null;
                                        if (valor instanceof java.util.Date) {
                                            dataObj = (java.util.Date) valor;
                                        } else if (valor instanceof java.sql.Date) {
                                            dataObj = new java.util.Date(((java.sql.Date) valor).getTime());
                                        } else {
                                            java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("dd/MM/yyyy");
                                            dataObj = sdf.parse(valor.toString());
                                        }
                                        java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("dd/MM/yyyy");
                                        texto = sdf.format(dataObj);
                                    } catch (Exception e) {
                                        texto = valor.toString();
                                    }
                                } else if (colunaNome.contains("gênero") || colunaNome.contains("genero")
                                        || colunaNome.contains("sexo")) {
                                    String genero = valor.toString().trim();

                                    if (genero.equals("0") || genero.equalsIgnoreCase("m")
                                            || genero.equalsIgnoreCase("masculino")) {
                                        texto = "Masculino";
                                    } else if (genero.equals("1") || genero.equalsIgnoreCase("f")
                                            || genero.equalsIgnoreCase("feminino")) {
                                        texto = "Feminino";
                                    } else if (genero.equalsIgnoreCase("o") || genero.equalsIgnoreCase("outro")) {
                                        texto = "Outro";
                                    } else {
                                        if (!genero.isEmpty()) {
                                            texto = genero.substring(0, 1).toUpperCase() + genero.substring(1).toLowerCase();
                                        } else {
                                            texto = "Não informado";
                                        }
                                    }
                                } else {
                                    texto = valor.toString();
                                }
                            } else {
                                texto = "";
                            }

                            // Truncar texto muito longo
                            String colunaNome = jTable.getColumnName(col).toLowerCase();
                            if (!colunaNome.contains("cpf") && !colunaNome.contains("cnpj")
                                    && !colunaNome.contains("telefone") && !colunaNome.contains("celular")
                                    && !colunaNome.contains("gênero") && !colunaNome.contains("genero")
                                    && !colunaNome.contains("sexo") && texto.length() > 30) {
                                texto = texto.substring(0, 27) + "...";
                            }

                            g2d.drawString(texto, x + 5, y);
                            x += larguras[col];
                        }
                        y += 18;

                        // Verificar se cabe na página
                        if (y > pageFormat.getImageableHeight() - 80) {
                            return NO_SUCH_PAGE;
                        }
                    }

                    // Rodapé premium
                    int pageHeight = (int) pageFormat.getImageableHeight();

                    // Linha decorativa no rodapé
                    g2d.setColor(gold);
                    g2d.setStroke(new java.awt.BasicStroke(1.5f));
                    g2d.drawLine(30, pageHeight - 60, (int) pageFormat.getImageableWidth() - 30, pageHeight - 60);

                    // Total de clientes
                    g2d.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 11));
                    g2d.setColor(black);
                    g2d.drawString("Total de clientes: ", 30, pageHeight - 45);
                    g2d.setColor(gold);
                    g2d.drawString(String.valueOf(jTable.getRowCount()), 130, pageHeight - 45);

                    // Estatísticas de gênero
                    int masculino = 0;
                    int feminino = 0;
                    int outro = 0;
                    int naoInformado = 0;

                    for (int i = 0; i < jTable.getColumnCount(); i++) {
                        String colunaNome = jTable.getColumnName(i).toLowerCase();
                        if (colunaNome.contains("gênero") || colunaNome.contains("genero")
                                || colunaNome.contains("sexo")) {

                            for (int row = 0; row < jTable.getRowCount(); row++) {
                                Object valor = jTable.getValueAt(row, i);
                                if (valor != null) {
                                    String genero = valor.toString().trim();

                                    if (genero.equals("0") || genero.equalsIgnoreCase("m")
                                            || genero.equalsIgnoreCase("masculino")) {
                                        masculino++;
                                    } else if (genero.equals("1") || genero.equalsIgnoreCase("f")
                                            || genero.equalsIgnoreCase("feminino")) {
                                        feminino++;
                                    } else if (genero.equalsIgnoreCase("o") || genero.equalsIgnoreCase("outro")) {
                                        outro++;
                                    } else if (!genero.isEmpty()) {
                                        outro++;
                                    } else {
                                        naoInformado++;
                                    }
                                } else {
                                    naoInformado++;
                                }
                            }
                            break;
                        }
                    }

                    // Exibir estatísticas de gênero
                    g2d.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 10));
                    g2d.setColor(lightBlack);
                    g2d.drawString("Distribuição por gênero: ", 30, pageHeight - 30);

                    // Criar barras de porcentagem
                    int total = jTable.getRowCount();
                    int barStartX = 160;
                    int barWidth = 200;
                    int barHeight = 12;
                    int barY = pageHeight - 35;

                    if (total > 0) {
                        // Barra de masculino
                        if (masculino > 0) {
                            int mascWidth = (masculino * barWidth) / total;
                            g2d.setColor(new java.awt.Color(51, 102, 153)); // Azul para masculino
                            g2d.fillRect(barStartX, barY, mascWidth, barHeight);
                            g2d.setColor(black);
                            g2d.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 9));
                            int percentual = (masculino * 100) / total;
                            g2d.drawString("♂ " + percentual + "%", barStartX + 5, barY + 10);
                        }

                        // Barra de feminino
                        if (feminino > 0) {
                            int femWidth = (feminino * barWidth) / total;
                            g2d.setColor(new java.awt.Color(204, 102, 153)); // Rosa para feminino
                            g2d.fillRect(barStartX + (masculino * barWidth) / total, barY, femWidth, barHeight);
                            g2d.setColor(black);
                            g2d.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 9));
                            int percentual = (feminino * 100) / total;
                            g2d.drawString("♀ " + percentual + "%", barStartX + (masculino * barWidth) / total + 5, barY + 10);
                        }

                        // Barra de outros
                        if (outro > 0) {
                            int outroWidth = (outro * barWidth) / total;
                            g2d.setColor(new java.awt.Color(102, 153, 102)); // Verde para outros
                            g2d.fillRect(barStartX + ((masculino + feminino) * barWidth) / total, barY, outroWidth, barHeight);
                            g2d.setColor(black);
                            g2d.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 9));
                            int percentual = (outro * 100) / total;
                            g2d.drawString("⚧ " + percentual + "%", barStartX + ((masculino + feminino) * barWidth) / total + 5, barY + 10);
                        }
                    }

                    // Número da página
                    g2d.setFont(new java.awt.Font("Segoe UI", java.awt.Font.ITALIC, 9));
                    g2d.setColor(lightBlack);
                    g2d.drawString("Página 1 de 1", (int) pageFormat.getImageableWidth() - 80, pageHeight - 20);

                    // Logo/assinatura
                    g2d.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 10));
                    g2d.setColor(gold);
                    g2d.drawString("© Sistema Premium", (int) pageFormat.getImageableWidth() - 100, pageHeight - 5);

                    return PAGE_EXISTS;
                }
            };

            job.setPrintable(printable);

            // Mostrar diálogo de impressão
            if (job.printDialog()) {
                job.print();
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Relatório premium gerado com sucesso!\n\n"
                        + "Para salvar como PDF, selecione 'Microsoft Print to PDF'\n"
                        + "ou outra impressora virtual de PDF na lista de impressoras.",
                        "Relatório Premium", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            }

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Erro ao gerar relatório premium: " + e.getMessage(),
                    "Erro", javax.swing.JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_jBtnOk1ActionPerformed

    private void jCboGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCboGeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCboGeneroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgConsultaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgConsultaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgConsultaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgConsultaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgConsultaClientes dialog = new JDlgConsultaClientes(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnConsultar;
    private javax.swing.JButton jBtnOk;
    private javax.swing.JButton jBtnOk1;
    private javax.swing.JComboBox<String> jCboGenero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable;
    private javax.swing.JTextField jTxtNome;
    // End of variables declaration//GEN-END:variables
}
