package view;

import dao.VendedorDAO;
import java.util.ArrayList;
import java.util.List;
import tools.Util;

public class JDlgConsultaVendedor extends javax.swing.JDialog {

    ControllerConsultasVendedor controllerConsultasVendedor;

    public JDlgConsultaVendedor(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Consultar Vendedores");
        controllerConsultasVendedor = new ControllerConsultasVendedor();
        VendedorDAO vendedorDAO = new VendedorDAO();
        List lista = new ArrayList();
        controllerConsultasVendedor.setList(lista);
        jTable.setModel(controllerConsultasVendedor);

        // === FORMATAÇÃO AUTOMÁTICA DE SALDO COM R$ ===
        rps_jTxtSalario.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyReleased(java.awt.event.KeyEvent evt) {
                // Remove tudo que não for número
                String texto = rps_jTxtSalario.getText().replaceAll("[^0-9]", "");

                if (texto.isEmpty()) {
                    rps_jTxtSalario.setText("R$ 0,00");
                    return;
                }

                // Garante pelo menos 3 dígitos (para manter 2 casas decimais)
                while (texto.length() < 3) {
                    texto = "0" + texto;
                }

                try {
                    double valor = Double.parseDouble(texto) / 100.0;
                    java.text.DecimalFormat df = new java.text.DecimalFormat("#,##0.00");
                    rps_jTxtSalario.setText("R$ " + df.format(valor));
                } catch (NumberFormatException e) {
                    // em caso de erro de conversão, reseta o campo
                    rps_jTxtSalario.setText("R$ 0,00");
                }
            }

            @Override
            public void keyTyped(java.awt.event.KeyEvent evt) {
                // bloqueia qualquer caractere que não seja número
                char c = evt.getKeyChar();
                if (!Character.isDigit(c)) {
                    evt.consume();
                }
            }
        });

        // inicializa o campo bonitinho
        rps_jTxtSalario.setText("R$ 0,00");
        rps_jTxtSalario.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        rps_jTxtSalario.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));
        rps_jTxtSalario.setForeground(new java.awt.Color(34, 139, 34)); // verde "saldo positivo"
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jBtnOk = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTxtNome = new javax.swing.JTextField();
        jBtnConsultar = new javax.swing.JButton();
        jBtnOk1 = new javax.swing.JButton();
        rps_jTxtSalario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable);

        jBtnOk.setText("OK");
        jBtnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnOkActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome");

        jBtnConsultar.setText("Consultar");
        jBtnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConsultarActionPerformed(evt);
            }
        });

        jBtnOk1.setText("IMPRIMIR");
        jBtnOk1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnOk1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Salário Maior que ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBtnOk1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtnOk))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jTxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(rps_jTxtSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jBtnConsultar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jLabel2)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnConsultar)
                    .addComponent(rps_jTxtSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnOk)
                    .addComponent(jBtnOk1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnOkActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jBtnOkActionPerformed

    private void jTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            jBtnOkActionPerformed(null);
        }
    }//GEN-LAST:event_jTableMouseClicked

    private void jBtnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConsultarActionPerformed
        VendedorDAO vendedorDAO = new VendedorDAO();
        List lista;
        if ((jTxtNome.getText().isEmpty() == false)
                && (rps_jTxtSalario.getText().isEmpty() == false)) {
            lista = (List) vendedorDAO.listNomeSalario(jTxtNome.getText(),
                    Util.strToDouble(rps_jTxtSalario.getText()));
        } else if (jTxtNome.getText().isEmpty() == false) {
            lista = (List) vendedorDAO.listNome(jTxtNome.getText());
        } else if (rps_jTxtSalario.getText().isEmpty() == false) {
            lista = (List) vendedorDAO.listSalario(Util.strToDouble(rps_jTxtSalario.getText()));
        } else {
            lista = (List) vendedorDAO.listAll();
        }
        controllerConsultasVendedor.setList(lista);


    }//GEN-LAST:event_jBtnConsultarActionPerformed

    private void jBtnOk1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnOk1ActionPerformed
        try {
            // Verifica se há dados na tabela
            if (jTable.getRowCount() == 0) {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Não há dados para imprimir!\nRealize uma consulta primeiro.",
                        "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
                return;
            }

            // Configurar o serviço de impressão
            java.awt.print.PrinterJob job = java.awt.print.PrinterJob.getPrinterJob();
            job.setJobName("Relatório de Vendedores");

            // Criar um Printable personalizado
            java.awt.print.Printable printable = new java.awt.print.Printable() {
                @Override
                public int print(java.awt.Graphics graphics, java.awt.print.PageFormat pageFormat, int pageIndex)
                        throws java.awt.print.PrinterException {

                    if (pageIndex > 0) {
                        return NO_SUCH_PAGE;
                    }

                    java.awt.Graphics2D g2d = (java.awt.Graphics2D) graphics;
                    g2d.translate(pageFormat.getImageableX(), pageFormat.getImageableY());

                    // Configurar fonte
                    g2d.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 16));

                    // Título
                    g2d.drawString("RELATÓRIO DE VENDEDORES", 100, 50);

                    // Data
                    g2d.setFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 10));
                    String data = new java.text.SimpleDateFormat("dd/MM/yyyy HH:mm:ss").format(new java.util.Date());
                    g2d.drawString("Gerado em: " + data, 100, 70);

                    // Filtros aplicados
                    g2d.setFont(new java.awt.Font("Arial", java.awt.Font.ITALIC, 9));
                    String filtros = "";

                    // Filtro por Nome
                    if (!jTxtNome.getText().isEmpty()) {
                        filtros += "Nome: " + jTxtNome.getText();
                    }

                    // Filtro por Salário maior que
                    if (!rps_jTxtSalario.getText().isEmpty()) {
                        try {
                            double salario = Double.parseDouble(rps_jTxtSalario.getText());
                            if (!filtros.isEmpty()) {
                                filtros += " | ";
                            }
                            filtros += "Salário > R$ " + String.format("%.2f", salario);
                        } catch (NumberFormatException e) {
                            // Ignorar se o valor não for numérico
                        }
                    }

                    if (!filtros.isEmpty()) {
                        g2d.drawString("Filtros: " + filtros, 100, 85);
                    }

                    // Desenhar tabela
                    int y = 110;

                    // Cabeçalho
                    g2d.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 11));
                    g2d.setColor(new java.awt.Color(51, 102, 153));

                    // Calcular largura das colunas
                    int numColunas = jTable.getColumnCount();
                    int[] larguras = new int[numColunas];
                    int larguraTotal = 0;

                    // Ajustar larguras baseado no conteúdo
                    for (int i = 0; i < numColunas; i++) {
                        String colunaNome = jTable.getColumnName(i).toLowerCase();

                        // Ajustar largura baseada no nome da coluna
                        if (colunaNome.contains("salário") || colunaNome.contains("salario")) {
                            larguras[i] = 100; // Largura para salários
                        } else if (colunaNome.contains("comissão") || colunaNome.contains("comissao")) {
                            larguras[i] = 90; // Largura para comissões
                        } else if (colunaNome.contains("nome") || colunaNome.contains("vendedor")) {
                            larguras[i] = 150; // Maior largura para nomes
                        } else if (colunaNome.contains("cpf") || colunaNome.contains("matrícula") || colunaNome.contains("matricula")) {
                            larguras[i] = 110; // Largura para documentos/matrículas
                        } else if (colunaNome.contains("email")) {
                            larguras[i] = 160; // Largura para emails
                        } else if (colunaNome.contains("telefone") || colunaNome.contains("celular")) {
                            larguras[i] = 110; // Largura para telefones
                        } else if (colunaNome.contains("data") || colunaNome.contains("admissão") || colunaNome.contains("admissao")) {
                            larguras[i] = 100; // Largura para datas
                        } else if (colunaNome.contains("meta") || colunaNome.contains("vendas")) {
                            larguras[i] = 100; // Largura para metas/vendas
                        } else if (colunaNome.contains("endereço") || colunaNome.contains("endereco")) {
                            larguras[i] = 180; // Largura maior para endereços
                        } else {
                            larguras[i] = 120; // Largura padrão
                        }
                        larguraTotal += larguras[i];
                    }

                    // Desenhar cabeçalhos
                    int x = 30;
                    for (int i = 0; i < numColunas; i++) {
                        String coluna = jTable.getColumnName(i);
                        g2d.fillRect(x, y - 12, larguras[i], 20);
                        g2d.setColor(java.awt.Color.WHITE);
                        g2d.drawString(coluna, x + 5, y);
                        g2d.setColor(new java.awt.Color(51, 102, 153));
                        g2d.drawRect(x, y - 12, larguras[i], 20);
                        x += larguras[i];
                    }

                    y += 15;

                    // Dados
                    g2d.setFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 10));
                    g2d.setColor(java.awt.Color.BLACK);

                    for (int row = 0; row < jTable.getRowCount(); row++) {
                        x = 30;

                        // Alternar cor de fundo das linhas
                        if (row % 2 == 0) {
                            g2d.setColor(new java.awt.Color(240, 240, 240));
                            g2d.fillRect(30, y - 8, larguraTotal, 15);
                            g2d.setColor(java.awt.Color.BLACK);
                        }

                        for (int col = 0; col < numColunas; col++) {
                            Object valor = jTable.getValueAt(row, col);
                            String texto = "";

                            // Formatar valores específicos
                            if (valor != null) {
                                String colunaNome = jTable.getColumnName(col).toLowerCase();

                                // Formatar valores monetários (salário, comissão, etc.)
                                if (colunaNome.contains("salário") || colunaNome.contains("salario")
                                        || colunaNome.contains("comissão") || colunaNome.contains("comissao")
                                        || colunaNome.contains("meta") || colunaNome.contains("vendas")
                                        || colunaNome.contains("valor")) {
                                    try {
                                        double numValor = Double.parseDouble(valor.toString());
                                        texto = String.format("R$ %.2f", numValor);
                                    } catch (NumberFormatException e) {
                                        texto = valor.toString();
                                    }
                                } // Formatar CPF
                                else if (colunaNome.contains("cpf")) {
                                    String cpf = valor.toString().replaceAll("[^0-9]", "");
                                    if (cpf.length() == 11) {
                                        texto = cpf.substring(0, 3) + "."
                                                + cpf.substring(3, 6) + "."
                                                + cpf.substring(6, 9) + "-"
                                                + cpf.substring(9);
                                    } else {
                                        texto = valor.toString();
                                    }
                                } // Formatar telefone
                                else if (colunaNome.contains("telefone") || colunaNome.contains("celular")) {
                                    String tel = valor.toString().replaceAll("[^0-9]", "");
                                    if (tel.length() == 10) {
                                        texto = "(" + tel.substring(0, 2) + ") "
                                                + tel.substring(2, 6) + "-"
                                                + tel.substring(6);
                                    } else if (tel.length() == 11) {
                                        texto = "(" + tel.substring(0, 2) + ") "
                                                + tel.substring(2, 7) + "-"
                                                + tel.substring(7);
                                    } else {
                                        texto = valor.toString();
                                    }
                                } // Formatar datas
                                else if (colunaNome.contains("data") || colunaNome.contains("admissão")
                                        || colunaNome.contains("admissao") || colunaNome.contains("nascimento")) {
                                    try {
                                        java.util.Date dataObj = null;
                                        if (valor instanceof java.util.Date) {
                                            dataObj = (java.util.Date) valor;
                                        } else if (valor instanceof java.sql.Date) {
                                            dataObj = new java.util.Date(((java.sql.Date) valor).getTime());
                                        } else {
                                            java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("dd/MM/yyyy");
                                            dataObj = sdf.parse(valor.toString());
                                        }
                                        java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("dd/MM/yyyy");
                                        texto = sdf.format(dataObj);
                                    } catch (Exception e) {
                                        texto = valor.toString();
                                    }
                                } // Porcentagem (para comissão)
                                else if (colunaNome.contains("porcentagem") || colunaNome.contains("percentual")) {
                                    try {
                                        double percentual = Double.parseDouble(valor.toString());
                                        texto = String.format("%.1f%%", percentual);
                                    } catch (NumberFormatException e) {
                                        texto = valor.toString();
                                    }
                                } else {
                                    texto = valor.toString();
                                }
                            }

                            // Truncar texto muito longo (não aplicar a valores monetários, CPF, telefone, datas)
                            String colunaNome = jTable.getColumnName(col).toLowerCase();
                            if (!colunaNome.contains("salário") && !colunaNome.contains("salario")
                                    && !colunaNome.contains("comissão") && !colunaNome.contains("comissao")
                                    && !colunaNome.contains("cpf") && !colunaNome.contains("telefone")
                                    && !colunaNome.contains("celular") && !colunaNome.contains("data")
                                    && !colunaNome.contains("valor") && texto.length() > 25) {
                                texto = texto.substring(0, 22) + "...";
                            }

                            g2d.drawString(texto, x + 5, y);
                            g2d.drawRect(x, y - 8, larguras[col], 15);
                            x += larguras[col];
                        }
                        y += 18;

                        // Verificar se cabe na página
                        if (y > pageFormat.getImageableHeight() - 50) {
                            return NO_SUCH_PAGE;
                        }
                    }

                    // Rodapé com estatísticas
                    y = (int) pageFormat.getImageableHeight() - 60;
                    g2d.setFont(new java.awt.Font("Arial", java.awt.Font.ITALIC, 10));
                    g2d.drawString("Total de vendedores: " + jTable.getRowCount(), 30, y);

                    // Calcular totais e médias
                    double totalSalarios = 0;
                    double totalComissoes = 0;
                    double maiorSalario = 0;
                    double menorSalario = Double.MAX_VALUE;
                    int contSalarios = 0;

                    // Encontrar colunas de salário e comissão
                    int colSalario = -1;
                    int colComissao = -1;

                    for (int i = 0; i < jTable.getColumnCount(); i++) {
                        String colunaNome = jTable.getColumnName(i).toLowerCase();
                        if (colunaNome.contains("salário") || colunaNome.contains("salario")) {
                            colSalario = i;
                        }
                        if (colunaNome.contains("comissão") || colunaNome.contains("comissao")) {
                            colComissao = i;
                        }
                    }

                    // Calcular estatísticas de salário
                    if (colSalario != -1) {
                        for (int row = 0; row < jTable.getRowCount(); row++) {
                            Object valor = jTable.getValueAt(row, colSalario);
                            if (valor != null) {
                                try {
                                    double salario = Double.parseDouble(valor.toString());
                                    totalSalarios += salario;
                                    contSalarios++;

                                    if (salario > maiorSalario) {
                                        maiorSalario = salario;
                                    }
                                    if (salario < menorSalario) {
                                        menorSalario = salario;
                                    }
                                } catch (NumberFormatException e) {
                                    // Ignorar valores não numéricos
                                }
                            }
                        }

                        // Calcular média
                        double mediaSalarios = (contSalarios > 0) ? totalSalarios / contSalarios : 0;

                        g2d.drawString(String.format("Média salarial: R$ %.2f", mediaSalarios), 30, y + 15);
                        g2d.drawString(String.format("Maior salário: R$ %.2f", maiorSalario), 30, y + 30);
                        g2d.drawString(String.format("Menor salário: R$ %.2f", menorSalario), 30, y + 45);
                    }

                    // Calcular total de comissões
                    if (colComissao != -1) {
                        for (int row = 0; row < jTable.getRowCount(); row++) {
                            Object valor = jTable.getValueAt(row, colComissao);
                            if (valor != null) {
                                try {
                                    totalComissoes += Double.parseDouble(valor.toString());
                                } catch (NumberFormatException e) {
                                    // Ignorar valores não numéricos
                                }
                            }
                        }

                        g2d.drawString(String.format("Total comissões: R$ %.2f", totalComissoes), 200, y + 15);
                    }

                    return PAGE_EXISTS;
                }
            };

            job.setPrintable(printable);

            // Mostrar diálogo de impressão
            if (job.printDialog()) {
                job.print();
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Relatório de vendedores enviado para impressão!\n\n"
                        + "Para salvar como PDF, selecione 'Microsoft Print to PDF'\n"
                        + "ou outra impressora virtual de PDF.",
                        "Sucesso", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            }

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Erro ao gerar relatório: " + e.getMessage(),
                    "Erro", javax.swing.JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_jBtnOk1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgConsultaVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgConsultaVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgConsultaVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgConsultaVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgConsultaVendedor dialog = new JDlgConsultaVendedor(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnConsultar;
    private javax.swing.JButton jBtnOk;
    private javax.swing.JButton jBtnOk1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable;
    private javax.swing.JTextField jTxtNome;
    private javax.swing.JTextField rps_jTxtSalario;
    // End of variables declaration//GEN-END:variables
}
