package view;

import bean.RpsUsuarios;
import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;
import tools.Util;
import dao.UsuariosDAO;

public class JDlgUsuarios extends javax.swing.JDialog {

    private boolean incluir;
    private MaskFormatter mascaraCpf, mascaraDataNasc;

    public JDlgUsuarios(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        iniciarRelogio("Cadastro de Usuários"); // coloque o nome do usuário logado aqui
        setLocationRelativeTo(null);
        jLabel1.setForeground(Color.WHITE);
        jLabel2.setForeground(Color.WHITE);
        jLabel3.setForeground(Color.WHITE);
        jLabel4.setForeground(Color.WHITE);
        jLabel5.setForeground(Color.WHITE);
        jLabel6.setForeground(Color.WHITE);
        jLabel7.setForeground(Color.WHITE);
        rps_jChbAtivo.setForeground(Color.WHITE);

        ImageIcon backgroundIcon = new ImageIcon(getClass().getResource("/img/telaUsuario.jpg"));
        Image image = backgroundIcon.getImage().getScaledInstance(getWidth(), getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(image);
        JLabel background = new JLabel(scaledIcon);
        background.setBounds(0, 0, getWidth(), getHeight());
        getContentPane().add(background);
        getContentPane().setComponentZOrder(background, getContentPane().getComponentCount() - 1);

        Util.habilitar(false, rps_jBtnConfirmar, rps_jBtnCancelar, rps_jTxtCodigo, rps_jTxtNome, rps_jTxtApelido, rps_jFmtCpf, rps_jFmtDataNascimento, rps_jCboNivel, rps_jChbAtivo, rps_jPwdSenha);
        try {
            mascaraCpf = new MaskFormatter("###.###.###-##");
            mascaraDataNasc = new MaskFormatter("##/##/####");
            rps_jFmtCpf.setFormatterFactory(new DefaultFormatterFactory(mascaraCpf));
            rps_jFmtDataNascimento.setFormatterFactory(new DefaultFormatterFactory(mascaraDataNasc));
        } catch (ParseException ex) {
            Logger.getLogger(JDlgUsuarios.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void iniciarRelogio(String nomeUsuario) {
        javax.swing.Timer timer = new javax.swing.Timer(1000, e -> {
            java.text.SimpleDateFormat sdfHora = new java.text.SimpleDateFormat("HH:mm:ss");
            java.text.SimpleDateFormat sdfData = new java.text.SimpleDateFormat("EEEE, dd 'de' MMMM 'de' yyyy");

            String hora = sdfHora.format(new java.util.Date());
            String data = sdfData.format(new java.util.Date());

            // Capitaliza o dia da semana
            data = data.substring(0, 1).toUpperCase() + data.substring(1);

            // Define título com usuário, data e hora
            setTitle(nomeUsuario + " | " + data + " | " + hora);
        });
        timer.start();
    }

    public void beanView(RpsUsuarios usuarios) {
        rps_jTxtCodigo.setText(Util.intToStr(usuarios.getRpsIdusuarios()));
        rps_jTxtNome.setText(usuarios.getRpsNome());
        rps_jTxtApelido.setText(usuarios.getRpsApelido());
        rps_jFmtCpf.setText(usuarios.getRpsCpf());
        rps_jFmtDataNascimento.setText(Util.dateToStr(usuarios.getRpsDataNascimento()));
        rps_jPwdSenha.setText(usuarios.getRpsSenha());
        rps_jCboNivel.setSelectedIndex(usuarios.getRpsNivel());
        if (usuarios.getRpsAtivo().equals("S") == true) {
            rps_jChbAtivo.setSelected(true);
        } else {
            rps_jChbAtivo.setSelected(false);
        }
    }

    public RpsUsuarios viewBean() {
        RpsUsuarios Rpsusuarios = new RpsUsuarios();
        int cod = Util.strToInt(rps_jTxtCodigo.getText());
        Rpsusuarios.setRpsIdusuarios(cod);
        Rpsusuarios.setRpsNome(rps_jTxtNome.getText());
        Rpsusuarios.setRpsApelido(rps_jTxtApelido.getText());
        Rpsusuarios.setRpsCpf(rps_jFmtCpf.getText());
        Rpsusuarios.setRpsDataNascimento(Util.strToDate(rps_jFmtDataNascimento.getText()));
        Rpsusuarios.setRpsSenha(rps_jPwdSenha.getText());
        Rpsusuarios.setRpsNivel(rps_jCboNivel.getSelectedIndex());
        if (rps_jChbAtivo.isSelected() == true) {
            Rpsusuarios.setRpsAtivo("S");
        } else {
            Rpsusuarios.setRpsAtivo("N");
        }
        return Rpsusuarios;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rps_jBtnIncluir = new javax.swing.JButton();
        rps_jBtnAlterar = new javax.swing.JButton();
        rps_jBtnExcluir = new javax.swing.JButton();
        rps_jBtnConfirmar = new javax.swing.JButton();
        rps_jBtnCancelar = new javax.swing.JButton();
        rps_jBtnPesquisar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        rps_jTxtCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        rps_jTxtNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        rps_jTxtApelido = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        rps_jFmtCpf = new javax.swing.JFormattedTextField();
        rps_jFmtDataNascimento = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        rps_jPwdSenha = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        rps_jChbAtivo = new javax.swing.JCheckBox();
        rps_jCboNivel = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        rps_jBtnIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/incluir.png"))); // NOI18N
        rps_jBtnIncluir.setText("Incluir");
        rps_jBtnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rps_jBtnIncluirActionPerformed(evt);
            }
        });

        rps_jBtnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alterar.png"))); // NOI18N
        rps_jBtnAlterar.setText("Alterar");
        rps_jBtnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rps_jBtnAlterarActionPerformed(evt);
            }
        });

        rps_jBtnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Excluir.png"))); // NOI18N
        rps_jBtnExcluir.setText("Excluir");
        rps_jBtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rps_jBtnExcluirActionPerformed(evt);
            }
        });

        rps_jBtnConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/gravar.png"))); // NOI18N
        rps_jBtnConfirmar.setText("Confirmar");
        rps_jBtnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rps_jBtnConfirmarActionPerformed(evt);
            }
        });

        rps_jBtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancelar.png"))); // NOI18N
        rps_jBtnCancelar.setText("Cancelar");
        rps_jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rps_jBtnCancelarActionPerformed(evt);
            }
        });

        rps_jBtnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pesquisar.png"))); // NOI18N
        rps_jBtnPesquisar.setText("Pesquisar");
        rps_jBtnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rps_jBtnPesquisarActionPerformed(evt);
            }
        });

        jLabel1.setDisplayedMnemonic('c');
        jLabel1.setText("Código");

        jLabel2.setDisplayedMnemonic('n');
        jLabel2.setText("Nome");

        rps_jTxtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rps_jTxtNomeActionPerformed(evt);
            }
        });

        jLabel3.setDisplayedMnemonic('a');
        jLabel3.setText("Apelido");

        rps_jTxtApelido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rps_jTxtApelidoActionPerformed(evt);
            }
        });

        jLabel4.setDisplayedMnemonic('c');
        jLabel4.setText("CPF");

        jLabel5.setDisplayedMnemonic('d');
        jLabel5.setText("Data de Nascimento");

        rps_jFmtCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rps_jFmtCpfActionPerformed(evt);
            }
        });

        rps_jFmtDataNascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rps_jFmtDataNascimentoActionPerformed(evt);
            }
        });

        jLabel6.setDisplayedMnemonic('s');
        jLabel6.setText("Senha");

        jLabel7.setDisplayedMnemonic('n');
        jLabel7.setText("Nível");

        rps_jChbAtivo.setMnemonic('a');
        rps_jChbAtivo.setText("Ativo");
        rps_jChbAtivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rps_jChbAtivoActionPerformed(evt);
            }
        });

        rps_jCboNivel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Funcionário", "Convidado" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(rps_jTxtApelido, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rps_jFmtCpf))
                                .addGap(431, 431, 431))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(rps_jBtnIncluir)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(rps_jBtnAlterar))
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(rps_jBtnExcluir)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(rps_jBtnConfirmar)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(rps_jBtnCancelar)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(rps_jBtnPesquisar))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(60, 60, 60)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(rps_jCboNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(rps_jFmtDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel5)))))
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(rps_jTxtCodigo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))
                                    .addComponent(rps_jTxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rps_jPwdSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rps_jChbAtivo)
                        .addGap(29, 29, 29))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rps_jTxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rps_jTxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(12, 12, 12)
                .addComponent(rps_jTxtApelido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rps_jFmtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rps_jFmtDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rps_jCboNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rps_jPwdSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(rps_jChbAtivo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rps_jBtnIncluir)
                    .addComponent(rps_jBtnAlterar)
                    .addComponent(rps_jBtnExcluir)
                    .addComponent(rps_jBtnConfirmar)
                    .addComponent(rps_jBtnCancelar)
                    .addComponent(rps_jBtnPesquisar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rps_jTxtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rps_jTxtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rps_jTxtNomeActionPerformed

    private void rps_jTxtApelidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rps_jTxtApelidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rps_jTxtApelidoActionPerformed

    private void rps_jBtnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rps_jBtnAlterarActionPerformed
        if (rps_jTxtCodigo.getText().trim().isEmpty()) {
            Util.mensagem("Pesquise um Usuário antes de Alterar");
            return;
        }
        Util.habilitar(true, rps_jBtnConfirmar, rps_jBtnCancelar, rps_jTxtCodigo, rps_jTxtNome, rps_jTxtApelido, rps_jFmtCpf, rps_jFmtDataNascimento, rps_jCboNivel, rps_jChbAtivo, rps_jPwdSenha);
        Util.habilitar(false, rps_jBtnIncluir, rps_jBtnExcluir, rps_jBtnAlterar, rps_jBtnPesquisar);
        Util.habilitar(false, rps_jTxtCodigo);
        rps_jTxtNome.grabFocus();
        incluir = false;
    }//GEN-LAST:event_rps_jBtnAlterarActionPerformed

    private void rps_jBtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rps_jBtnExcluirActionPerformed
        if (rps_jTxtCodigo.getText().trim().isEmpty()) {
            Util.mensagem("Pesquise um Usuário antes de Excluir");
            return;
        }

        if (Util.pergunta("Deseja excluir ?") == true) {
            UsuariosDAO usuariosDAO = new UsuariosDAO();
            RpsUsuarios rpsUsuarios = viewBean();
            usuariosDAO.delete(rpsUsuarios);
        }
        Util.limpar(rps_jTxtCodigo, rps_jTxtNome, rps_jTxtApelido, rps_jFmtCpf, rps_jFmtDataNascimento, rps_jCboNivel, rps_jChbAtivo, rps_jPwdSenha);
    }//GEN-LAST:event_rps_jBtnExcluirActionPerformed

    private void rps_jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rps_jBtnCancelarActionPerformed
        Util.habilitar(false, rps_jBtnConfirmar, rps_jBtnCancelar, rps_jTxtCodigo, rps_jTxtNome, rps_jTxtApelido, rps_jFmtCpf, rps_jFmtDataNascimento, rps_jCboNivel, rps_jChbAtivo, rps_jPwdSenha);
        Util.habilitar(true, rps_jBtnIncluir, rps_jBtnExcluir, rps_jBtnAlterar, rps_jBtnPesquisar);
        Util.limpar(rps_jTxtCodigo, rps_jTxtNome, rps_jTxtApelido, rps_jFmtCpf, rps_jFmtDataNascimento, rps_jCboNivel, rps_jChbAtivo, rps_jPwdSenha);
    }//GEN-LAST:event_rps_jBtnCancelarActionPerformed

    private void rps_jFmtCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rps_jFmtCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rps_jFmtCpfActionPerformed

    private void rps_jChbAtivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rps_jChbAtivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rps_jChbAtivoActionPerformed

    private void rps_jFmtDataNascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rps_jFmtDataNascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rps_jFmtDataNascimentoActionPerformed

    private void rps_jBtnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rps_jBtnPesquisarActionPerformed
        JDlgUsuariosPesquisar jDlgUsuariosPesquisar = new JDlgUsuariosPesquisar(null, true);
        jDlgUsuariosPesquisar.setTelaAnterior(this);
        jDlgUsuariosPesquisar.setVisible(true);
    }//GEN-LAST:event_rps_jBtnPesquisarActionPerformed

    private void rps_jBtnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rps_jBtnIncluirActionPerformed
        Util.habilitar(true, rps_jBtnConfirmar, rps_jBtnCancelar, rps_jTxtCodigo, rps_jTxtNome, rps_jTxtApelido, rps_jFmtCpf, rps_jFmtDataNascimento, rps_jCboNivel, rps_jChbAtivo, rps_jPwdSenha);
        Util.limpar(rps_jTxtCodigo, rps_jTxtNome, rps_jTxtApelido, rps_jFmtCpf, rps_jFmtDataNascimento, rps_jCboNivel, rps_jChbAtivo, rps_jPwdSenha);
        Util.habilitar(false, rps_jBtnIncluir, rps_jBtnExcluir, rps_jBtnAlterar, rps_jBtnPesquisar);
        rps_jTxtCodigo.grabFocus();
        incluir = true;
    }//GEN-LAST:event_rps_jBtnIncluirActionPerformed

    private void rps_jBtnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rps_jBtnConfirmarActionPerformed
        UsuariosDAO usuariosDAO = new UsuariosDAO();
        RpsUsuarios Rpsusuarios = viewBean();
        if (incluir == true) {
            usuariosDAO.insert(Rpsusuarios);

        } else {
            usuariosDAO.update(Rpsusuarios);
        }
        Util.habilitar(false, rps_jBtnConfirmar, rps_jBtnCancelar, rps_jTxtCodigo, rps_jTxtNome, rps_jTxtApelido, rps_jFmtCpf, rps_jFmtDataNascimento, rps_jCboNivel, rps_jChbAtivo, rps_jPwdSenha);
        Util.habilitar(true, rps_jBtnIncluir, rps_jBtnExcluir, rps_jBtnAlterar, rps_jBtnPesquisar);
        Util.limpar(rps_jTxtCodigo, rps_jTxtNome, rps_jTxtApelido, rps_jFmtCpf, rps_jFmtDataNascimento, rps_jCboNivel, rps_jChbAtivo, rps_jPwdSenha);
    }//GEN-LAST:event_rps_jBtnConfirmarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgUsuarios dialog = new JDlgUsuarios(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton rps_jBtnAlterar;
    private javax.swing.JButton rps_jBtnCancelar;
    private javax.swing.JButton rps_jBtnConfirmar;
    private javax.swing.JButton rps_jBtnExcluir;
    private javax.swing.JButton rps_jBtnIncluir;
    private javax.swing.JButton rps_jBtnPesquisar;
    private javax.swing.JComboBox<String> rps_jCboNivel;
    private javax.swing.JCheckBox rps_jChbAtivo;
    private javax.swing.JFormattedTextField rps_jFmtCpf;
    private javax.swing.JFormattedTextField rps_jFmtDataNascimento;
    private javax.swing.JPasswordField rps_jPwdSenha;
    private javax.swing.JTextField rps_jTxtApelido;
    private javax.swing.JTextField rps_jTxtCodigo;
    private javax.swing.JTextField rps_jTxtNome;
    // End of variables declaration//GEN-END:variables
}
