package view;

import bean.RpsClientes;
import bean.RpsVendedor;
import dao.VendasDAO;
import java.util.ArrayList;
import java.util.List;
import dao.ClientesDAO;
import dao.VendedorDAO;

public class JDlgConsultaVendas extends javax.swing.JDialog {

    ControllerConsultasVendas controllerConsultasVendas;

    public JDlgConsultaVendas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Consultar Clientes");
        controllerConsultasVendas = new ControllerConsultasVendas();
        VendasDAO vendasDAO = new VendasDAO();
        List lista = new ArrayList();
        controllerConsultasVendas.setList(lista);
        jTable.setModel(controllerConsultasVendas);

        ClientesDAO clientesDAO = new ClientesDAO();
        List lista1 = (List) clientesDAO.listAll();
        for (int i = 0; i < lista1.size(); i++) {
            rps_jCboClientes.addItem((RpsClientes) lista1.get(i));
        }

        VendedorDAO vendedorDAO = new VendedorDAO();
        List lista2 = (List) vendedorDAO.listAll();
        for (int i = 0; i < lista2.size(); i++) {
            rps_jCboVendedor.addItem((RpsVendedor) lista2.get(i));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jBtnOk = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jBtnConsultar = new javax.swing.JButton();
        jBtnOk1 = new javax.swing.JButton();
        rps_jCboClientes = new javax.swing.JComboBox<RpsClientes>();
        rps_jCboVendedor = new javax.swing.JComboBox<RpsVendedor>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable);

        jBtnOk.setText("OK");
        jBtnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnOkActionPerformed(evt);
            }
        });

        jLabel1.setText("Cliente");

        jLabel2.setText("Vendedor");

        jBtnConsultar.setText("Consultar");
        jBtnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConsultarActionPerformed(evt);
            }
        });

        jBtnOk1.setText("IMPRIMIR");
        jBtnOk1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnOk1ActionPerformed(evt);
            }
        });

        rps_jCboClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rps_jCboClientesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBtnOk1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtnOk))
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(rps_jCboClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rps_jCboVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(jBtnConsultar))
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rps_jCboClientes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rps_jCboVendedor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(45, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtnConsultar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBtnOk)
                            .addComponent(jBtnOk1))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnOkActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jBtnOkActionPerformed

    private void jTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            jBtnOkActionPerformed(null);
        }
    }//GEN-LAST:event_jTableMouseClicked

    private void jBtnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConsultarActionPerformed
        VendasDAO usuariosDAO = new VendasDAO();
        List lista;
        if ((rps_jCboClientes.getSelectedIndex() != -1)
                && (rps_jCboVendedor.getSelectedIndex() != -1)) {
            lista = (List) usuariosDAO.listClienteVendedor(
                    ((RpsClientes) rps_jCboClientes.getSelectedItem()),
                    ((RpsVendedor) rps_jCboVendedor.getSelectedItem()));
        } else if (rps_jCboClientes.getSelectedIndex() != -1) {
            lista = (List) usuariosDAO.listCliente(
                    ((RpsClientes) rps_jCboClientes.getSelectedItem()));
        } else if (rps_jCboVendedor.getSelectedIndex() != -1) {
            lista = (List) usuariosDAO.listVendedor(
                    ((RpsVendedor) rps_jCboVendedor.getSelectedItem()));
        } else {
            lista = (List) usuariosDAO.listAll();
        }
        controllerConsultasVendas.setList(lista);


    }//GEN-LAST:event_jBtnConsultarActionPerformed

    private void jBtnOk1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnOk1ActionPerformed
        try {
            // Verifica se há dados na tabela
            if (jTable.getRowCount() == 0) {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Não há dados para imprimir!\nRealize uma consulta primeiro.",
                        "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
                return;
            }

            // Configurar o serviço de impressão
            java.awt.print.PrinterJob job = java.awt.print.PrinterJob.getPrinterJob();
            job.setJobName("Relatório de Vendas");

            // Criar um Printable personalizado
            java.awt.print.Printable printable = new java.awt.print.Printable() {
                @Override
                public int print(java.awt.Graphics graphics, java.awt.print.PageFormat pageFormat, int pageIndex)
                        throws java.awt.print.PrinterException {

                    if (pageIndex > 0) {
                        return NO_SUCH_PAGE;
                    }

                    java.awt.Graphics2D g2d = (java.awt.Graphics2D) graphics;
                    g2d.translate(pageFormat.getImageableX(), pageFormat.getImageableY());

                    // Configurar fonte
                    g2d.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 16));

                    // Título
                    g2d.drawString("RELATÓRIO DE VENDAS", 100, 50);

                    // Data
                    g2d.setFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 10));
                    String data = new java.text.SimpleDateFormat("dd/MM/yyyy HH:mm:ss").format(new java.util.Date());
                    g2d.drawString("Gerado em: " + data, 100, 70);

                    // Filtros aplicados
                    g2d.setFont(new java.awt.Font("Arial", java.awt.Font.ITALIC, 9));
                    String filtros = "";

                    // Filtro por Cliente (combo box)
                    if (rps_jCboClientes.getSelectedItem() != null) {
                        Object itemCliente = rps_jCboClientes.getSelectedItem();
                        String clienteSelecionado = itemCliente.toString().trim();

                        // Verificar se não é o item padrão (como "Selecione..." ou "Todos")
                        if (!clienteSelecionado.isEmpty()
                                && !clienteSelecionado.equals("Selecione...")
                                && !clienteSelecionado.equals("Todos")
                                && !clienteSelecionado.equals("0")
                                && !clienteSelecionado.equals("")) {

                            if (!filtros.isEmpty()) {
                                filtros += " | ";
                            }
                            filtros += "Cliente: " + clienteSelecionado;
                        }
                    }

                    // Filtro por Vendedor (combo box)
                    if (rps_jCboVendedor.getSelectedItem() != null) {
                        Object itemVendedor = rps_jCboVendedor.getSelectedItem();
                        String vendedorSelecionado = itemVendedor.toString().trim();

                        // Verificar se não é o item padrão (como "Selecione..." ou "Todos")
                        if (!vendedorSelecionado.isEmpty()
                                && !vendedorSelecionado.equals("Selecione...")
                                && !vendedorSelecionado.equals("Todos")
                                && !vendedorSelecionado.equals("0")
                                && !vendedorSelecionado.equals("")) {

                            if (!filtros.isEmpty()) {
                                filtros += " | ";
                            }
                            filtros += "Vendedor: " + vendedorSelecionado;
                        }
                    }

                    if (!filtros.isEmpty()) {
                        g2d.drawString("Filtros: " + filtros, 100, 85);
                    }

                    // Desenhar tabela
                    int y = 110;

                    // Cabeçalho
                    g2d.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 11));
                    g2d.setColor(new java.awt.Color(51, 102, 153));

                    // Calcular largura das colunas
                    int numColunas = jTable.getColumnCount();
                    int[] larguras = new int[numColunas];
                    int larguraTotal = 0;

                    // Ajustar larguras baseado no tipo de dado das colunas
                    for (int i = 0; i < numColunas; i++) {
                        String colunaNome = jTable.getColumnName(i).toLowerCase();

                        // Ajustar largura baseada no nome da coluna
                        if (colunaNome.contains("cliente") || colunaNome.contains("vendedor") || colunaNome.contains("nome")) {
                            larguras[i] = 150; // Largura maior para nomes
                        } else if (colunaNome.contains("produto") || colunaNome.contains("descrição") || colunaNome.contains("descricao")) {
                            larguras[i] = 180; // Largura maior para produtos/descrições
                        } else if (colunaNome.contains("valor") || colunaNome.contains("preço") || colunaNome.contains("preco")
                                || colunaNome.contains("total") || colunaNome.contains("subtotal")) {
                            larguras[i] = 100; // Largura para valores
                        } else if (colunaNome.contains("quantidade") || colunaNome.contains("qtd") || colunaNome.contains("qtde")) {
                            larguras[i] = 80; // Largura menor para quantidades
                        } else if (colunaNome.contains("data") || colunaNome.contains("venda") || colunaNome.contains("emissão")
                                || colunaNome.contains("emissao")) {
                            larguras[i] = 100; // Largura para datas
                        } else if (colunaNome.contains("código") || colunaNome.contains("codigo") || colunaNome.contains("id")
                                || colunaNome.contains("nº") || colunaNome.contains("numero") || colunaNome.contains("pedido")) {
                            larguras[i] = 80; // Largura para códigos/IDs
                        } else if (colunaNome.contains("status") || colunaNome.contains("situação") || colunaNome.contains("situacao")) {
                            larguras[i] = 100; // Largura para status
                        } else if (colunaNome.contains("forma") || colunaNome.contains("pagamento") || colunaNome.contains("pagto")) {
                            larguras[i] = 120; // Largura para forma de pagamento
                        } else {
                            larguras[i] = 120; // Largura padrão para outras colunas
                        }
                        larguraTotal += larguras[i];
                    }

                    // Desenhar cabeçalhos
                    int x = 30;
                    for (int i = 0; i < numColunas; i++) {
                        String coluna = jTable.getColumnName(i);
                        g2d.fillRect(x, y - 12, larguras[i], 20);
                        g2d.setColor(java.awt.Color.WHITE);
                        g2d.drawString(coluna, x + 5, y);
                        g2d.setColor(new java.awt.Color(51, 102, 153));
                        g2d.drawRect(x, y - 12, larguras[i], 20);
                        x += larguras[i];
                    }

                    y += 15;

                    // Dados
                    g2d.setFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 10));
                    g2d.setColor(java.awt.Color.BLACK);

                    for (int row = 0; row < jTable.getRowCount(); row++) {
                        x = 30;

                        // Alternar cor de fundo das linhas
                        if (row % 2 == 0) {
                            g2d.setColor(new java.awt.Color(240, 240, 240));
                            g2d.fillRect(30, y - 8, larguraTotal, 15);
                            g2d.setColor(java.awt.Color.BLACK);
                        }

                        for (int col = 0; col < numColunas; col++) {
                            Object valor = jTable.getValueAt(row, col);
                            String texto = "";

                            if (valor != null) {
                                String colunaNome = jTable.getColumnName(col).toLowerCase();

                                // Formatar dados específicos
                                if (colunaNome.contains("valor") || colunaNome.contains("preço") || colunaNome.contains("preco")
                                        || colunaNome.contains("total") || colunaNome.contains("subtotal")
                                        || colunaNome.contains("desconto") || colunaNome.contains("acréscimo")
                                        || colunaNome.contains("acrescimo")) {
                                    // Formatar valores monetários
                                    try {
                                        double numValor = Double.parseDouble(valor.toString());
                                        texto = String.format("R$ %.2f", numValor);
                                    } catch (NumberFormatException e) {
                                        texto = valor.toString();
                                    }
                                } else if (colunaNome.contains("quantidade") || colunaNome.contains("qtd") || colunaNome.contains("qtde")) {
                                    // Formatar quantidades
                                    try {
                                        double qtd = Double.parseDouble(valor.toString());
                                        if (qtd == Math.floor(qtd)) {
                                            texto = String.format("%.0f", qtd); // Inteiro
                                        } else {
                                            texto = String.format("%.2f", qtd); // Decimal
                                        }
                                    } catch (NumberFormatException e) {
                                        texto = valor.toString();
                                    }
                                } else if (colunaNome.contains("data") || colunaNome.contains("venda") || colunaNome.contains("emissão")
                                        || colunaNome.contains("emissao") || colunaNome.contains("entrega")) {
                                    // Formatar datas
                                    try {
                                        java.util.Date dataObj = null;
                                        if (valor instanceof java.util.Date) {
                                            dataObj = (java.util.Date) valor;
                                        } else if (valor instanceof java.sql.Date) {
                                            dataObj = new java.util.Date(((java.sql.Date) valor).getTime());
                                        } else if (valor instanceof java.sql.Timestamp) {
                                            dataObj = new java.util.Date(((java.sql.Timestamp) valor).getTime());
                                        } else {
                                            // Tentar parsear string
                                            java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("dd/MM/yyyy");
                                            dataObj = sdf.parse(valor.toString());
                                        }
                                        java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("dd/MM/yyyy");
                                        texto = sdf.format(dataObj);
                                    } catch (Exception e) {
                                        // Tentar formato com hora
                                        try {
                                            java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("dd/MM/yyyy HH:mm");
                                            java.util.Date dataObj = sdf.parse(valor.toString());
                                            texto = sdf.format(dataObj);
                                        } catch (Exception e2) {
                                            texto = valor.toString();
                                        }
                                    }
                                } else if (colunaNome.contains("cliente") || colunaNome.contains("vendedor")
                                        || colunaNome.contains("nome")) {
                                    // Formatar nomes - primeira letra maiúscula
                                    String nome = valor.toString().trim();
                                    if (!nome.isEmpty()) {
                                        // Separar por espaço e capitalizar cada palavra
                                        String[] palavras = nome.split("\\s+");
                                        StringBuilder nomeFormatado = new StringBuilder();
                                        for (String palavra : palavras) {
                                            if (!palavra.isEmpty()) {
                                                if (nomeFormatado.length() > 0) {
                                                    nomeFormatado.append(" ");
                                                }
                                                nomeFormatado.append(palavra.substring(0, 1).toUpperCase())
                                                        .append(palavra.substring(1).toLowerCase());
                                            }
                                        }
                                        texto = nomeFormatado.toString();
                                    } else {
                                        texto = nome;
                                    }
                                } else if (colunaNome.contains("status") || colunaNome.contains("situação")
                                        || colunaNome.contains("situacao")) {
                                    // Formatar status (primeira letra maiúscula)
                                    String status = valor.toString().trim().toLowerCase();
                                    if (!status.isEmpty()) {
                                        texto = status.substring(0, 1).toUpperCase() + status.substring(1);

                                        // Mapear valores comuns
                                        if (status.equals("p")) {
                                            texto = "Pendente";
                                        } else if (status.equals("c")) {
                                            texto = "Concluído";
                                        } else if (status.equals("a")) {
                                            texto = "Aguardando";
                                        } else if (status.equals("f")) {
                                            texto = "Faturado";
                                        } else if (status.equals("e")) {
                                            texto = "Entregue";
                                        } else if (status.equals("cancelado") || status.equals("canc")) {
                                            texto = "Cancelado";
                                        }
                                    } else {
                                        texto = status;
                                    }
                                } else if (colunaNome.contains("forma") || colunaNome.contains("pagamento")
                                        || colunaNome.contains("pagto")) {
                                    // Formatar forma de pagamento
                                    String formaPag = valor.toString().trim().toLowerCase();
                                    if (!formaPag.isEmpty()) {
                                        texto = formaPag.substring(0, 1).toUpperCase() + formaPag.substring(1);

                                        // Mapear abreviações comuns
                                        if (formaPag.equals("cc") || formaPag.equals("cartao")) {
                                            texto = "Cartão de Crédito";
                                        } else if (formaPag.equals("cd") || formaPag.equals("debito")) {
                                            texto = "Cartão de Débito";
                                        } else if (formaPag.equals("b") || formaPag.equals("boleto")) {
                                            texto = "Boleto";
                                        } else if (formaPag.equals("p") || formaPag.equals("pix")) {
                                            texto = "PIX";
                                        } else if (formaPag.equals("d") || formaPag.equals("dinheiro")) {
                                            texto = "Dinheiro";
                                        }
                                    } else {
                                        texto = formaPag;
                                    }
                                } else {
                                    texto = valor.toString();
                                }
                            }

                            // Truncar texto muito longo (não aplicar a valores monetários, datas, quantidades)
                            String colunaNome = jTable.getColumnName(col).toLowerCase();
                            if (!colunaNome.contains("valor") && !colunaNome.contains("preço") && !colunaNome.contains("preco")
                                    && !colunaNome.contains("total") && !colunaNome.contains("subtotal")
                                    && !colunaNome.contains("quantidade") && !colunaNome.contains("qtd")
                                    && !colunaNome.contains("data") && !colunaNome.contains("código")
                                    && !colunaNome.contains("codigo") && !colunaNome.contains("id")
                                    && texto.length() > 25) {
                                texto = texto.substring(0, 22) + "...";
                            }

                            g2d.drawString(texto, x + 5, y);
                            g2d.drawRect(x, y - 8, larguras[col], 15);
                            x += larguras[col];
                        }
                        y += 18;

                        // Verificar se cabe na página
                        if (y > pageFormat.getImageableHeight() - 80) {
                            return NO_SUCH_PAGE;
                        }
                    }

                    // Rodapé com estatísticas
                    y = (int) pageFormat.getImageableHeight() - 60;
                    g2d.setFont(new java.awt.Font("Arial", java.awt.Font.ITALIC, 10));
                    g2d.drawString("Total de vendas: " + jTable.getRowCount(), 30, y);

                    // Calcular estatísticas financeiras
                    double valorTotalVendas = 0;
                    double maiorVenda = 0;
                    double menorVenda = Double.MAX_VALUE;
                    int totalItens = 0;

                    // Encontrar colunas relevantes
                    int colValor = -1;
                    int colQuantidade = -1;
                    int colCliente = -1;
                    int colVendedor = -1;

                    for (int i = 0; i < jTable.getColumnCount(); i++) {
                        String colunaNome = jTable.getColumnName(i).toLowerCase();
                        if (colunaNome.contains("valor") || colunaNome.contains("total") || colunaNome.contains("preço")) {
                            colValor = i;
                        }
                        if (colunaNome.contains("quantidade") || colunaNome.contains("qtd")) {
                            colQuantidade = i;
                        }
                        if (colunaNome.contains("cliente")) {
                            colCliente = i;
                        }
                        if (colunaNome.contains("vendedor")) {
                            colVendedor = i;
                        }
                    }

                    // Calcular totais
                    if (colValor != -1) {
                        for (int row = 0; row < jTable.getRowCount(); row++) {
                            Object valor = jTable.getValueAt(row, colValor);
                            if (valor != null) {
                                try {
                                    double valorVenda = Double.parseDouble(valor.toString());
                                    valorTotalVendas += valorVenda;

                                    if (valorVenda > maiorVenda) {
                                        maiorVenda = valorVenda;
                                    }
                                    if (valorVenda < menorVenda) {
                                        menorVenda = valorVenda;
                                    }
                                } catch (NumberFormatException e) {
                                    // Ignorar valores não numéricos
                                }
                            }
                        }

                        // Calcular média
                        double mediaVendas = (jTable.getRowCount() > 0) ? valorTotalVendas / jTable.getRowCount() : 0;

                        g2d.drawString(String.format("Valor total: R$ %.2f", valorTotalVendas), 30, y + 15);
                        g2d.drawString(String.format("Média por venda: R$ %.2f", mediaVendas), 30, y + 30);
                        g2d.drawString(String.format("Maior venda: R$ %.2f", maiorVenda), 200, y + 15);
                        g2d.drawString(String.format("Menor venda: R$ %.2f", menorVenda), 200, y + 30);
                    }

                    // Calcular total de itens
                    if (colQuantidade != -1) {
                        for (int row = 0; row < jTable.getRowCount(); row++) {
                            Object valor = jTable.getValueAt(row, colQuantidade);
                            if (valor != null) {
                                try {
                                    totalItens += Integer.parseInt(valor.toString());
                                } catch (NumberFormatException e) {
                                    try {
                                        totalItens += (int) Double.parseDouble(valor.toString());
                                    } catch (NumberFormatException e2) {
                                        // Ignorar valores não numéricos
                                    }
                                }
                            }
                        }

                        g2d.drawString("Total de itens: " + totalItens, 200, y + 45);
                    }

                    return PAGE_EXISTS;
                }
            };

            job.setPrintable(printable);

            // Mostrar diálogo de impressão
            if (job.printDialog()) {
                job.print();
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Relatório de vendas enviado para impressão!\n\n"
                        + "Para salvar como PDF, selecione 'Microsoft Print to PDF'\n"
                        + "ou outra impressora virtual de PDF.",
                        "Sucesso", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            }

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Erro ao gerar relatório: " + e.getMessage(),
                    "Erro", javax.swing.JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_jBtnOk1ActionPerformed

    private void rps_jCboClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rps_jCboClientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rps_jCboClientesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgConsultaVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgConsultaVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgConsultaVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgConsultaVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgConsultaVendas dialog = new JDlgConsultaVendas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnConsultar;
    private javax.swing.JButton jBtnOk;
    private javax.swing.JButton jBtnOk1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable;
    private javax.swing.JComboBox<RpsClientes> rps_jCboClientes;
    private javax.swing.JComboBox<RpsVendedor> rps_jCboVendedor;
    // End of variables declaration//GEN-END:variables
}
